<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 11 Análisis bivariable | Introducción a la Estadística para Científicos de Datos con R</title>
  <meta name="description" content="Libro de introducción a la estadística" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 11 Análisis bivariable | Introducción a la Estadística para Científicos de Datos con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Libro de introducción a la estadística" />
  <meta name="github-repo" content="https://github.com/rvaquerizo02/Estadistica-data-scientist" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 11 Análisis bivariable | Introducción a la Estadística para Científicos de Datos con R" />
  
  <meta name="twitter:description" content="Libro de introducción a la estadística" />
  

<meta name="author" content="Raul Vaquerizo" />


<meta name="date" content="2023-05-05" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="probabilidad-distribuciones.html"/>
<link rel="next" href="muestreo-inferencia.html"/>
<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.24/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introducción a la Estadística para Científicos de Datos con R/a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#objetivos"><i class="fa fa-check"></i><b>1.1</b> Objetivos</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#entorno-de-trabajo"><i class="fa fa-check"></i><b>1.2</b> Entorno de trabajo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>2</b> Datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="datos.html"><a href="datos.html#qué-son-los-datos"><i class="fa fa-check"></i><b>2.1</b> Qué son los datos</a></li>
<li class="chapter" data-level="2.2" data-path="datos.html"><a href="datos.html#tipos-de-datos"><i class="fa fa-check"></i><b>2.2</b> Tipos de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="datos.html"><a href="datos.html#datos-internos"><i class="fa fa-check"></i><b>2.2.1</b> Datos internos</a></li>
<li class="chapter" data-level="2.2.2" data-path="datos.html"><a href="datos.html#datos-externos"><i class="fa fa-check"></i><b>2.2.2</b> Datos externos:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="datos.html"><a href="datos.html#almacenamiento-de-datos"><i class="fa fa-check"></i><b>2.3</b> Almacenamiento de datos</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="datos.html"><a href="datos.html#sistemas-operacionales"><i class="fa fa-check"></i><b>2.3.1</b> Sistemas operacionales</a></li>
<li class="chapter" data-level="2.3.2" data-path="datos.html"><a href="datos.html#sistemas-informacionales-tradicionales"><i class="fa fa-check"></i><b>2.3.2</b> Sistemas informacionales tradicionales</a></li>
<li class="chapter" data-level="2.3.3" data-path="datos.html"><a href="datos.html#data-lake"><i class="fa fa-check"></i><b>2.3.3</b> Data Lake</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="datos.html"><a href="datos.html#todo-es-álgebra-lineal"><i class="fa fa-check"></i><b>2.4</b> Todo es álgebra lineal</a></li>
<li class="chapter" data-level="2.5" data-path="datos.html"><a href="datos.html#como-se-disponen-los-datos"><i class="fa fa-check"></i><b>2.5</b> Como se disponen los datos</a></li>
<li class="chapter" data-level="2.6" data-path="datos.html"><a href="datos.html#tipos-de-variables"><i class="fa fa-check"></i><b>2.6</b> Tipos de Variables</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="datos.html"><a href="datos.html#variables-cuantitativas"><i class="fa fa-check"></i><b>2.6.1</b> Variables cuantitativas</a></li>
<li class="chapter" data-level="2.6.2" data-path="datos.html"><a href="datos.html#variables-cualitativas.-factores"><i class="fa fa-check"></i><b>2.6.2</b> Variables cualitativas. Factores</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="datos.html"><a href="datos.html#el-rol-de-las-variables-en-los-datos"><i class="fa fa-check"></i><b>2.7</b> El rol de las variables en los datos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html"><i class="fa fa-check"></i><b>3</b> Manejo de datos con R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#universo-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Universo tidyverse</a></li>
<li class="chapter" data-level="3.2" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#selección-de-registros"><i class="fa fa-check"></i><b>3.2</b> Selección de registros</a></li>
<li class="chapter" data-level="3.3" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#selección-de-columnas"><i class="fa fa-check"></i><b>3.3</b> Selección de columnas</a></li>
<li class="chapter" data-level="3.4" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#creación-o-actualización-de-variables"><i class="fa fa-check"></i><b>3.4</b> Creación o actualización de variables</a></li>
<li class="chapter" data-level="3.5" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#ordenar-datos"><i class="fa fa-check"></i><b>3.5</b> Ordenar datos</a></li>
<li class="chapter" data-level="3.6" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#sumarizar-valores"><i class="fa fa-check"></i><b>3.6</b> Sumarizar valores</a></li>
<li class="chapter" data-level="3.7" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#combinación-de-acciones"><i class="fa fa-check"></i><b>3.7</b> Combinación de acciones</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html"><i class="fa fa-check"></i><b>4</b> Uniones de tablas con R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#uniones-verticales"><i class="fa fa-check"></i><b>4.1</b> Uniones verticales</a></li>
<li class="chapter" data-level="4.2" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#uniones-horizontales-o-join"><i class="fa fa-check"></i><b>4.2</b> Uniones horizontales o <em>join</em></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#inner-join"><i class="fa fa-check"></i><b>4.2.1</b> Inner join</a></li>
<li class="chapter" data-level="4.2.2" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#left-join"><i class="fa fa-check"></i><b>4.2.2</b> Left join</a></li>
<li class="chapter" data-level="4.2.3" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#anti-join"><i class="fa fa-check"></i><b>4.2.3</b> Anti join</a></li>
<li class="chapter" data-level="4.2.4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#librería-sqldf"><i class="fa fa-check"></i><b>4.2.4</b> Librería sqldf</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#duplicidades-en-las-uniones-de-tablas"><i class="fa fa-check"></i><b>4.3</b> Duplicidades en las uniones de tablas</a></li>
<li class="chapter" data-level="4.4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#referencias"><i class="fa fa-check"></i><b>4.4</b> Referencias</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html"><i class="fa fa-check"></i><b>5</b> Representación gráfica básica con ggplot</a>
<ul>
<li class="chapter" data-level="5.1" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#histogramas"><i class="fa fa-check"></i><b>5.1</b> Histogramas</a></li>
<li class="chapter" data-level="5.2" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-densidad"><i class="fa fa-check"></i><b>5.2</b> Gráficos de densidad</a></li>
<li class="chapter" data-level="5.3" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-caja-boxplot"><i class="fa fa-check"></i><b>5.3</b> Gráficos de caja (boxplot)</a></li>
<li class="chapter" data-level="5.4" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-tarta"><i class="fa fa-check"></i><b>5.4</b> Gráficos de tarta</a></li>
<li class="chapter" data-level="5.5" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-barras"><i class="fa fa-check"></i><b>5.5</b> Gráficos de barras</a></li>
<li class="chapter" data-level="5.6" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-líneas"><i class="fa fa-check"></i><b>5.6</b> Gráficos de líneas</a></li>
<li class="chapter" data-level="5.7" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráfico-de-dispersión"><i class="fa fa-check"></i><b>5.7</b> Gráfico de dispersión</a></li>
<li class="chapter" data-level="5.8" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#múltiples-gráficos-con-gridextra"><i class="fa fa-check"></i><b>5.8</b> Múltiples gráficos con gridExtra</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html"><i class="fa fa-check"></i><b>6</b> Descripción numérica de variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#transformar-datos-en-información"><i class="fa fa-check"></i><b>6.1</b> Transformar datos en información</a></li>
<li class="chapter" data-level="6.2" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#caso-práctico.-campaña-de-venta-cruzada"><i class="fa fa-check"></i><b>6.2</b> Caso práctico. Campaña de venta cruzada</a></li>
<li class="chapter" data-level="6.3" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#el-rol-de-las-variables-en-el-conjunto-de-datos"><i class="fa fa-check"></i><b>6.3</b> El rol de las variables en el conjunto de datos</a></li>
<li class="chapter" data-level="6.4" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#análisis-descriptivos-de-los-datos"><i class="fa fa-check"></i><b>6.4</b> Análisis descriptivos de los datos</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#descritivos-en-variables-cualitativas-factores"><i class="fa fa-check"></i><b>6.4.1</b> Descritivos en variables cualitativas (factores)</a></li>
<li class="chapter" data-level="6.4.2" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#descritivos-en-variables-cuantitativas"><i class="fa fa-check"></i><b>6.4.2</b> Descritivos en variables cuantitativas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html"><i class="fa fa-check"></i><b>7</b> Descripción gráfica de datos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html#descripción-gráfica-de-factores"><i class="fa fa-check"></i><b>7.1</b> Descripción gráfica de factores</a></li>
<li class="chapter" data-level="7.2" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html#descripción-gráfica-de-variables-numéricas"><i class="fa fa-check"></i><b>7.2</b> Descripción gráfica de variables numéricas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="problemas-datos.html"><a href="problemas-datos.html"><i class="fa fa-check"></i><b>8</b> Problemas con los datos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="problemas-datos.html"><a href="problemas-datos.html#problemática-con-factores"><i class="fa fa-check"></i><b>8.1</b> Problemática con factores</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-niveles-de-pocos-registros"><i class="fa fa-check"></i><b>8.1.1</b> Factores con niveles de pocos registros</a></li>
<li class="chapter" data-level="8.1.2" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-que-aparecen-como-variables-numéricas"><i class="fa fa-check"></i><b>8.1.2</b> Factores que aparecen como variables numéricas</a></li>
<li class="chapter" data-level="8.1.3" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-un-gran-número-de-niveles"><i class="fa fa-check"></i><b>8.1.3</b> Factores con un gran número de niveles</a></li>
<li class="chapter" data-level="8.1.4" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-valores-perdidos"><i class="fa fa-check"></i><b>8.1.4</b> Factores con valores perdidos</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="problemas-datos.html"><a href="problemas-datos.html#problemas-con-variables-numéricas"><i class="fa fa-check"></i><b>8.2</b> Problemas con variables numéricas</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-modales"><i class="fa fa-check"></i><b>8.2.1</b> Valores modales</a></li>
<li class="chapter" data-level="8.2.2" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-atípicos"><i class="fa fa-check"></i><b>8.2.2</b> Valores atípicos</a></li>
<li class="chapter" data-level="8.2.3" data-path="problemas-datos.html"><a href="problemas-datos.html#variables-numéricas-como-factores"><i class="fa fa-check"></i><b>8.2.3</b> Variables numéricas como factores</a></li>
<li class="chapter" data-level="8.2.4" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-perdidos-en-variables-numéricas"><i class="fa fa-check"></i><b>8.2.4</b> Valores perdidos en variables numéricas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analisis-exploratorio-datos-EDA.html"><a href="analisis-exploratorio-datos-EDA.html"><i class="fa fa-check"></i><b>9</b> Análisis Exploratorio de Datos. EDA</a></li>
<li class="chapter" data-level="10" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html"><i class="fa fa-check"></i><b>10</b> Probabilidad y distribuciones</a>
<ul>
<li class="chapter" data-level="10.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#conceptos-básicos-de-probabilidad"><i class="fa fa-check"></i><b>10.1</b> Conceptos básicos de probabilidad</a></li>
<li class="chapter" data-level="10.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-un-evento"><i class="fa fa-check"></i><b>10.2</b> Distribución de un evento</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-conocidas"><i class="fa fa-check"></i><b>10.2.1</b> Distribuciones conocidas</a></li>
<li class="chapter" data-level="10.2.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#obtención-de-probabilidades-con-r"><i class="fa fa-check"></i><b>10.2.2</b> Obtención de probabilidades con R</a></li>
<li class="chapter" data-level="10.2.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#generación-de-números-aleatorios-con-r"><i class="fa fa-check"></i><b>10.2.3</b> Generación de números aleatorios con R</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-discretas"><i class="fa fa-check"></i><b>10.3</b> Distribuciones discretas</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-bernoulli"><i class="fa fa-check"></i><b>10.3.1</b> Distribución de Bernoulli</a></li>
<li class="chapter" data-level="10.3.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-binomial"><i class="fa fa-check"></i><b>10.3.2</b> Distribución binomial</a></li>
<li class="chapter" data-level="10.3.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-poisson"><i class="fa fa-check"></i><b>10.3.3</b> Distribución de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-continuas"><i class="fa fa-check"></i><b>10.4</b> Distribuciones continuas</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-uniforme"><i class="fa fa-check"></i><b>10.4.1</b> Distribución uniforme</a></li>
<li class="chapter" data-level="10.4.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-normal"><i class="fa fa-check"></i><b>10.4.2</b> Distribución normal</a></li>
<li class="chapter" data-level="10.4.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-gamma"><i class="fa fa-check"></i><b>10.4.3</b> Distribución gamma</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html"><i class="fa fa-check"></i><b>11</b> Análisis bivariable</a>
<ul>
<li class="chapter" data-level="11.1" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#variable-numérica-frente-a-variable-numérica"><i class="fa fa-check"></i><b>11.1</b> Variable numérica frente a variable numérica</a></li>
<li class="chapter" data-level="11.2" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#factores-frente-a-variables-numéricas"><i class="fa fa-check"></i><b>11.2</b> Factores frente a variables numéricas</a></li>
<li class="chapter" data-level="11.3" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#factores-frente-a-factores"><i class="fa fa-check"></i><b>11.3</b> Factores frente a factores</a></li>
<li class="chapter" data-level="11.4" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#propuesta-de-análisis-gráfico-para-el-análisis-bivariable"><i class="fa fa-check"></i><b>11.4</b> Propuesta de análisis gráfico para el análisis bivariable</a></li>
<li class="chapter" data-level="11.5" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#correlación-entre-factores.-la-v-de-cramer"><i class="fa fa-check"></i><b>11.5</b> Correlación entre factores. La V de Cramer</a></li>
<li class="chapter" data-level="11.6" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#agrupación-de-variables-cuantitativas"><i class="fa fa-check"></i><b>11.6</b> Agrupación de variables cuantitativas</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html"><i class="fa fa-check"></i><b>12</b> Muestreo e inferencia estadística</a>
<ul>
<li class="chapter" data-level="12.1" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo"><i class="fa fa-check"></i><b>12.1</b> Muestreo</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-aleatorio-simple"><i class="fa fa-check"></i><b>12.1.1</b> Muestreo aleatorio simple</a></li>
<li class="chapter" data-level="12.1.2" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-aleatorio-estratificado"><i class="fa fa-check"></i><b>12.1.2</b> Muestreo aleatorio estratificado</a></li>
<li class="chapter" data-level="12.1.3" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-por-conglomerados"><i class="fa fa-check"></i><b>12.1.3</b> Muestreo por conglomerados</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#inferencia-estadística"><i class="fa fa-check"></i><b>12.2</b> Inferencia estadística</a></li>
<li class="chapter" data-level="12.3" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#estimación-de-parámetros"><i class="fa fa-check"></i><b>12.3</b> Estimación de parámetros</a></li>
<li class="chapter" data-level="12.4" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>12.4</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="12.5" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#contrastes-de-hipótesis"><i class="fa fa-check"></i><b>12.5</b> Contrastes de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="regresion-lineal.html"><a href="regresion-lineal.html"><i class="fa fa-check"></i><b>13</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="13.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#modelo-de-regresión-lineal-simple"><i class="fa fa-check"></i><b>13.1</b> Modelo de regresión lineal simple</a></li>
<li class="chapter" data-level="13.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#el-coeficiente-de-determinación-o-r2"><i class="fa fa-check"></i><b>13.2</b> El coeficiente de determinación o <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="13.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#transformaciones-de-variables"><i class="fa fa-check"></i><b>13.3</b> Transformaciones de variables</a></li>
<li class="chapter" data-level="13.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#tramificación-de-variables-en-modelos-lineales"><i class="fa fa-check"></i><b>13.4</b> Tramificación de variables en modelos lineales</a></li>
<li class="chapter" data-level="13.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#factores-en-modelos-de-regresión"><i class="fa fa-check"></i><b>13.5</b> Factores en modelos de regresión</a></li>
<li class="chapter" data-level="13.6" data-path="regresion-lineal.html"><a href="regresion-lineal.html#modelo-de-regresión-lineal-múltiple"><i class="fa fa-check"></i><b>13.6</b> Modelo de regresión lineal múltiple</a></li>
<li class="chapter" data-level="13.7" data-path="regresion-lineal.html"><a href="regresion-lineal.html#métodos-de-selección-de-variables"><i class="fa fa-check"></i><b>13.7</b> Métodos de selección de variables</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-fordward"><i class="fa fa-check"></i><b>13.7.1</b> Método fordward</a></li>
<li class="chapter" data-level="13.7.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-backward"><i class="fa fa-check"></i><b>13.7.2</b> Método backward</a></li>
<li class="chapter" data-level="13.7.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-stepwise"><i class="fa fa-check"></i><b>13.7.3</b> Método stepwise</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="regresion-lineal.html"><a href="regresion-lineal.html#el-principio-de-parsimonia"><i class="fa fa-check"></i><b>13.8</b> El principio de parsimonia</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html"><i class="fa fa-check"></i><b>14</b> Introducción al diseño de experimentos</a>
<ul>
<li class="chapter" data-level="14.1" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#fundamentos-del-diseño-experimental"><i class="fa fa-check"></i><b>14.1</b> Fundamentos del diseño experimental</a></li>
<li class="chapter" data-level="14.2" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#fuentes-de-variabilidad"><i class="fa fa-check"></i><b>14.2</b> Fuentes de variabilidad</a></li>
<li class="chapter" data-level="14.3" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#planificación"><i class="fa fa-check"></i><b>14.3</b> Planificación</a></li>
<li class="chapter" data-level="14.4" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#bloquear-y-aleatorizar-factores"><i class="fa fa-check"></i><b>14.4</b> Bloquear y aleatorizar factores</a></li>
<li class="chapter" data-level="14.5" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#diseños-factoriales"><i class="fa fa-check"></i><b>14.5</b> Diseños factoriales</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#modelo-unifactorial.-ab-testing"><i class="fa fa-check"></i><b>14.5.1</b> Modelo unifactorial. A/B testing</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#modelos-bifactoriales.-interacciones-entre-variables"><i class="fa fa-check"></i><b>14.6</b> Modelos bifactoriales. Interacciones entre variables</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="modelos-GLM.html"><a href="modelos-GLM.html"><i class="fa fa-check"></i><b>15</b> Modelos GLM. Regresión logística y regresión de poisson</a>
<ul>
<li class="chapter" data-level="15.1" data-path="modelos-GLM.html"><a href="modelos-GLM.html#motivación-de-los-modelos-glm"><i class="fa fa-check"></i><b>15.1</b> Motivación de los modelos GLM</a></li>
<li class="chapter" data-level="15.2" data-path="modelos-GLM.html"><a href="modelos-GLM.html#la-función-de-enlace-en-los-modelos-glm"><i class="fa fa-check"></i><b>15.2</b> La función de enlace en los modelos GLM</a></li>
<li class="chapter" data-level="15.3" data-path="modelos-GLM.html"><a href="modelos-GLM.html#regresión-logística"><i class="fa fa-check"></i><b>15.3</b> Regresión logística</a></li>
<li class="chapter" data-level="15.4" data-path="modelos-GLM.html"><a href="modelos-GLM.html#regresión-de-poisson"><i class="fa fa-check"></i><b>15.4</b> Regresión de poisson</a></li>
<li class="chapter" data-level="15.5" data-path="modelos-GLM.html"><a href="modelos-GLM.html#los-glm-y-el-concepto-microsegmento"><i class="fa fa-check"></i><b>15.5</b> Los GLM y el concepto microsegmento</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html"><i class="fa fa-check"></i><b>16</b> Modelización estadística</a>
<ul>
<li class="chapter" data-level="16.1" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#establecer-un-método-para-la-modelización-estadística"><i class="fa fa-check"></i><b>16.1</b> Establecer un método para la modelización estadística</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><i class="fa fa-check"></i><b>17</b> Modelo de venta cruzada en el sector asegurador</a>
<ul>
<li class="chapter" data-level="17.1" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#un-método-de-moelización-estadística"><i class="fa fa-check"></i><b>17.1</b> Un método de moelización estadística</a></li>
<li class="chapter" data-level="17.2" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#conocimiento-de-los-datos"><i class="fa fa-check"></i><b>17.2</b> Conocimiento de los datos</a>
<ul>
<li class="chapter" data-level="17.2.1" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#muestreo.-datos-de-entrenamiento-datos-de-validación-datos-de-test-y-prueba-ciega."><i class="fa fa-check"></i><b>17.2.1</b> Muestreo. Datos de entrenamiento, datos de validación, datos de test y prueba ciega.</a></li>
<li class="chapter" data-level="17.2.2" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#aproximación-inicial-a-los-datos"><i class="fa fa-check"></i><b>17.2.2</b> Aproximación inicial a los datos</a></li>
<li class="chapter" data-level="17.2.3" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#creación-y-clasificación-de-factores"><i class="fa fa-check"></i><b>17.2.3</b> Creación y clasificación de factores</a></li>
</ul></li>
<li class="chapter" data-level="17.3" data-path="modelo-de-venta-cruzada-en-el-sector-asegurador.html"><a href="modelo-de-venta-cruzada-en-el-sector-asegurador.html#modelización"><i class="fa fa-check"></i><b>17.3</b> Modelización</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción a la Estadística para Científicos de Datos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="analisis-bivariable" class="section level1 hasAnchor" number="11">
<h1><span class="header-section-number">Capítulo 11</span> Análisis bivariable<a href="analisis-bivariable.html#analisis-bivariable" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>De nuevo se retoma el ejemplo que está sirviendo de hilo conductor para este ensayo, la campaña de marketing de venta cruzada en el sector asegurador <a href="https://www.kaggle.com/anmolkumar/health-insurance-cross-sell-prediction">que está disponible en Kaggle</a>. Una aseguradora española que opera en múltiples ramos quiere ofrecer seguro de automóviles a sus clientes del ramo de salud. Para ello se realizó un cuestionario a los clientes de forma que se marcó quienes de ellos estarían interesados en el producto de automóviles y quienes no. Se identificaron posibles tareas:</p>
<ul>
<li>Describir la cartera de clientes.</li>
<li><strong>Identificar que características de nuestros clientes pueden ser eficaces a la hora de crear una campaña comercial.</strong></li>
<li>Sugerir unas reglas para la elaboración de la campaña.</li>
</ul>
<div class="sourceCode" id="cb252"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb252-1"><a href="analisis-bivariable.html#cb252-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb252-2"><a href="analisis-bivariable.html#cb252-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(formattable)</span>
<span id="cb252-3"><a href="analisis-bivariable.html#cb252-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb252-4"><a href="analisis-bivariable.html#cb252-4" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./data/train.csv&quot;</span>)</span>
<span id="cb252-5"><a href="analisis-bivariable.html#cb252-5" aria-hidden="true" tabindex="-1"></a><span class="fu">formattable</span>(<span class="fu">head</span>(train,<span class="dv">5</span>))</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
id
</th>
<th style="text-align:right;">
Gender
</th>
<th style="text-align:right;">
Age
</th>
<th style="text-align:right;">
Driving_License
</th>
<th style="text-align:right;">
Region_Code
</th>
<th style="text-align:right;">
Previously_Insured
</th>
<th style="text-align:right;">
Vehicle_Age
</th>
<th style="text-align:right;">
Vehicle_Damage
</th>
<th style="text-align:right;">
Annual_Premium
</th>
<th style="text-align:right;">
Policy_Sales_Channel
</th>
<th style="text-align:right;">
Vintage
</th>
<th style="text-align:right;">
Response
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
<blockquote>
2 Years
</td>
<td style="text-align:right;">
Yes
</td>
<td style="text-align:right;">
40454
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
217
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
76
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1-2 Year
</td>
<td style="text-align:right;">
No
</td>
<td style="text-align:right;">
33536
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
<blockquote>
2 Years
</td>
<td style="text-align:right;">
Yes
</td>
<td style="text-align:right;">
38294
</td>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
&lt; 1 Year
</td>
<td style="text-align:right;">
No
</td>
<td style="text-align:right;">
28619
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:right;">
203
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
Female
</td>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
&lt; 1 Year
</td>
<td style="text-align:right;">
No
</td>
<td style="text-align:right;">
27496
</td>
<td style="text-align:right;">
152
</td>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
</blockquote>
</blockquote>
<p>Hasta el momento se ha descrito el conjunto de datos, se han determinado que roles juegan las variables dentro de ese conjunto de datos donde se estableció que la variable más relevante es <code>Response</code> ya que juega el rol de <strong>variable target</strong>. Esta variable toma valores 0 - no interesa 1 - interesa el producto, es decir, se distribuye según una binomial con parámetros n = 381.000 clientes y p = 0.1223 interesados, conocer la distribución ayuda a afrontar el análisis.</p>
<div class="sourceCode" id="cb253"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb253-1"><a href="analisis-bivariable.html#cb253-1" aria-hidden="true" tabindex="-1"></a><span class="fu">formattable</span>(train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Response) <span class="sc">%&gt;%</span> </span>
<span id="cb253-2"><a href="analisis-bivariable.html#cb253-2" aria-hidden="true" tabindex="-1"></a>              <span class="fu">summarise</span>(<span class="at">clientes =</span> <span class="fu">n</span>(),<span class="at">pct_clientes=</span><span class="fu">n</span>()<span class="sc">/</span><span class="fu">nrow</span>(train)))</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
Response
</th>
<th style="text-align:right;">
clientes
</th>
<th style="text-align:right;">
pct_clientes
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
334399
</td>
<td style="text-align:right;">
0.8774366
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
46710
</td>
<td style="text-align:right;">
0.1225634
</td>
</tr>
</tbody>
</table>
<p>En este capítulo el científico de datos comienza a estudiar la relación entre dos variables que pueden ser cuantitativas o factores. Esta categorización da lugar a 3 tipos de relaciones entre dos variables:</p>
<ul>
<li>Variable numérica frente a variable numérica</li>
<li>Variable numérica frente a factor</li>
<li>Factor frente a factor</li>
</ul>
<div id="variable-numérica-frente-a-variable-numérica" class="section level2 hasAnchor" number="11.1">
<h2><span class="header-section-number">11.1</span> Variable numérica frente a variable numérica<a href="analisis-bivariable.html#variable-numérica-frente-a-variable-numérica" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El inicio de la relación entre dos variables es la <strong>correlación</strong>. Esta medida bivariable pretende medir como la variación de una variable cuantitativa influye en otra variable cuantitativa. La cuestión fundamental es, a medida que se incrementa x, ¿qué sucede con y? Por ejemplo, a medida que una persona crece en altura, ¿cómo se incrementa su peso? Para ilustrar se realiza una simulación y un <strong>gráfico de dispersión</strong> para estudiar como se distribuyen los pares de variables (peso, altura)</p>
<div class="sourceCode" id="cb254"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb254-1"><a href="analisis-bivariable.html#cb254-1" aria-hidden="true" tabindex="-1"></a>personas <span class="ot">&lt;-</span> <span class="dv">100</span> </span>
<span id="cb254-2"><a href="analisis-bivariable.html#cb254-2" aria-hidden="true" tabindex="-1"></a>altura <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(personas, <span class="dv">170</span>, <span class="dv">20</span>)</span>
<span id="cb254-3"><a href="analisis-bivariable.html#cb254-3" aria-hidden="true" tabindex="-1"></a>peso <span class="ot">&lt;-</span> altura<span class="sc">/</span><span class="fl">2.85</span> <span class="sc">+</span> <span class="fu">rnorm</span>(personas, <span class="dv">10</span>, <span class="dv">5</span>)</span>
<span id="cb254-4"><a href="analisis-bivariable.html#cb254-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb254-5"><a href="analisis-bivariable.html#cb254-5" aria-hidden="true" tabindex="-1"></a><span class="fu">data.frame</span>(<span class="at">altura=</span>altura, <span class="at">peso=</span>peso) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x =</span> altura, <span class="at">y =</span> peso)) <span class="sc">+</span> </span>
<span id="cb254-6"><a href="analisis-bivariable.html#cb254-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>()</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-142-1.png" width="672" /></p>
<p>Aunque sean datos simulados es evidente, por como se ha hecho la simulación, que a medida que aumenta la altura aumenta el peso. Hay una medida estadística para describir esta situación, el coeficiente de correlación que en R se calcula mediante la función <code>cor</code>.</p>
<div class="sourceCode" id="cb255"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb255-1"><a href="analisis-bivariable.html#cb255-1" aria-hidden="true" tabindex="-1"></a><span class="fu">cor</span>(peso, altura)</span></code></pre></div>
<pre><code>## [1] 0.8651548</code></pre>
<p>Esta medida de 0.87 indica que peso y altura se relacionan positivamente, a medida que aumenta uno aumenta el otro pero no es una medida de graduación, sólo mide la <strong>fuerza</strong> de esa relación. El coeficiente de correlación es un valor que toma valores entre -1 y 1 donde -1 significa total correlación negativa (aumenta una implica que disminuye la otra variable), 0 significa que no existe ningún tipo de correlación y 1 la correlación positiva (aumenta una aumenta otra variable).</p>
<p>Simulando y representando las distintas formas de correlación se tiene:</p>
<div class="sourceCode" id="cb257"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb257-1"><a href="analisis-bivariable.html#cb257-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gridExtra)</span>
<span id="cb257-2"><a href="analisis-bivariable.html#cb257-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-3"><a href="analisis-bivariable.html#cb257-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlación positiva</span></span>
<span id="cb257-4"><a href="analisis-bivariable.html#cb257-4" aria-hidden="true" tabindex="-1"></a>observaciones <span class="ot">&lt;-</span> <span class="dv">1000</span> </span>
<span id="cb257-5"><a href="analisis-bivariable.html#cb257-5" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(observaciones, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb257-6"><a href="analisis-bivariable.html#cb257-6" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> x<span class="sc">/</span><span class="dv">5</span> <span class="sc">+</span> <span class="fu">rnorm</span>(observaciones, <span class="dv">0</span>, <span class="fl">0.1</span>)</span>
<span id="cb257-7"><a href="analisis-bivariable.html#cb257-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-8"><a href="analisis-bivariable.html#cb257-8" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x , y)) <span class="sc">+</span> </span>
<span id="cb257-9"><a href="analisis-bivariable.html#cb257-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">&quot;Correlación: &quot;</span>, <span class="fu">round</span>(<span class="fu">cor</span>(x,y),<span class="dv">3</span>)))</span>
<span id="cb257-10"><a href="analisis-bivariable.html#cb257-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-11"><a href="analisis-bivariable.html#cb257-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlación negativa</span></span>
<span id="cb257-12"><a href="analisis-bivariable.html#cb257-12" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(observaciones, <span class="dv">0</span>, <span class="dv">5</span>)</span>
<span id="cb257-13"><a href="analisis-bivariable.html#cb257-13" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">rpois</span>(observaciones, <span class="dv">3</span>) <span class="sc">-</span> x </span>
<span id="cb257-14"><a href="analisis-bivariable.html#cb257-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-15"><a href="analisis-bivariable.html#cb257-15" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x , y)) <span class="sc">+</span> </span>
<span id="cb257-16"><a href="analisis-bivariable.html#cb257-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">&quot;Correlación: &quot;</span>, <span class="fu">round</span>(<span class="fu">cor</span>(x,y),<span class="dv">3</span>)))</span>
<span id="cb257-17"><a href="analisis-bivariable.html#cb257-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-18"><a href="analisis-bivariable.html#cb257-18" aria-hidden="true" tabindex="-1"></a><span class="co"># Sin correlación </span></span>
<span id="cb257-19"><a href="analisis-bivariable.html#cb257-19" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(observaciones, <span class="dv">0</span>, <span class="dv">5</span>)</span>
<span id="cb257-20"><a href="analisis-bivariable.html#cb257-20" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> <span class="fu">runif</span>(observaciones)</span>
<span id="cb257-21"><a href="analisis-bivariable.html#cb257-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-22"><a href="analisis-bivariable.html#cb257-22" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x , y)) <span class="sc">+</span> </span>
<span id="cb257-23"><a href="analisis-bivariable.html#cb257-23" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">&quot;Correlación: &quot;</span>, <span class="fu">round</span>(<span class="fu">cor</span>(x,y),<span class="dv">3</span>)))</span>
<span id="cb257-24"><a href="analisis-bivariable.html#cb257-24" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-25"><a href="analisis-bivariable.html#cb257-25" aria-hidden="true" tabindex="-1"></a><span class="co"># Aparentemente sin correlación</span></span>
<span id="cb257-26"><a href="analisis-bivariable.html#cb257-26" aria-hidden="true" tabindex="-1"></a>x <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(observaciones, <span class="dv">0</span>, <span class="dv">1</span>)</span>
<span id="cb257-27"><a href="analisis-bivariable.html#cb257-27" aria-hidden="true" tabindex="-1"></a>y <span class="ot">&lt;-</span> x<span class="sc">^</span><span class="dv">2</span> <span class="sc">+</span> <span class="fu">runif</span>(observaciones, <span class="sc">-</span><span class="dv">1</span>,<span class="dv">1</span> )</span>
<span id="cb257-28"><a href="analisis-bivariable.html#cb257-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-29"><a href="analisis-bivariable.html#cb257-29" aria-hidden="true" tabindex="-1"></a>p4 <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(x,y) <span class="sc">%&gt;%</span>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(x , y)) <span class="sc">+</span> </span>
<span id="cb257-30"><a href="analisis-bivariable.html#cb257-30" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_point</span>() <span class="sc">+</span> <span class="fu">ggtitle</span>(<span class="fu">paste0</span>(<span class="st">&quot;Correlación: &quot;</span>, <span class="fu">round</span>(<span class="fu">cor</span>(x,y),<span class="dv">3</span>)))</span>
<span id="cb257-31"><a href="analisis-bivariable.html#cb257-31" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb257-32"><a href="analisis-bivariable.html#cb257-32" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1,p2,p3,p4)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-144-1.png" width="672" /></p>
<p>Se simulan 4 tipos distintos de correlación, correlación positiva, negativa (vistas con anterioridad); en el tercer caso no hay correlación, cuando ésta no existe los gráficos de dispersión generan polígonos como cuadrados, rectángulos o circunferencias ya que la disposición de los pares de puntos se debe a un comportamiento azaroso (una variable no afecta a otra). Sin embargo, se ilustra otro tipo de situación, el cuarto gráfico, donde es evidente que hay una relación entre las variables pero ésta no es lineal y por ello el coeficiente de correlación no es suficiente para identificar esta situación.</p>
<p>En el ejemplo de trabajo que hace de hilo conductor del ensayo no se realiza el análisis de correlaciones puesto que la variable principal para realizar un análisis bivariable es la variable target, la variable <code>Response</code>, que toma valores 0 si el cliente no está interesado en el seguro de automóviles y 1 si muestra interés en el producto. Por este motivo será más conveniente un análisis bivariable con un factor.</p>
</div>
<div id="factores-frente-a-variables-numéricas" class="section level2 hasAnchor" number="11.2">
<h2><span class="header-section-number">11.2</span> Factores frente a variables numéricas<a href="analisis-bivariable.html#factores-frente-a-variables-numéricas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Una de las variables es un factor, cada nivel de ese factor representa una categoría, ya no es un punto. Será necesario estudiar como son los valores que toma la variable numérica para cada nivel del factor. En el capítulo 7, en la descripción gráfica de datos se estudiaban los posibles valores que toma una variable mediante histogramas, gráficos de densidades y boxplot. En este caso se puede hacer uno de esos análisis gráficos para cada nivel del factor y así comparar ambas variables.</p>
<p>En el ejemplo de trabajo se tiene una variable target que toma valores 0 y 1, a continuación se estudia esa variable objetivo <code>Response</code> frente a la variable <code>Age</code> que indica la edad de los asegurados encuestados.</p>
<div class="sourceCode" id="cb258"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb258-1"><a href="analisis-bivariable.html#cb258-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb258-2"><a href="analisis-bivariable.html#cb258-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-145-1.png" width="672" /></p>
<p>Es necesario especificar que la variable es un factor, en este caso <code>Response</code> es numérica y a efectos prácticos se sigue manteniendo como numérica. Si no se especifica que es un factor se tendría la siguiente situación:</p>
<div class="sourceCode" id="cb259"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb259-1"><a href="analisis-bivariable.html#cb259-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">group=</span>Response, <span class="at">fill=</span>Response)) <span class="sc">+</span> </span>
<span id="cb259-2"><a href="analisis-bivariable.html#cb259-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_histogram</span>()</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-146-1.png" width="672" /></p>
<p>No tiene sentido realizar una escala continua de un factor, es un problema habitual cuando se trabaja con factores en R. En cualquier caso, emplear un histograma de este tipo no sirve porque se están contando registros y si una de las categorías del factor tiene menos observaciones no se podrá comparar su comportamiento. Pero se dispone de los gráficos de densidad que permiten estudiar mediante una función continua la distribución de los valores.</p>
<div class="sourceCode" id="cb260"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb260-1"><a href="analisis-bivariable.html#cb260-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb260-2"><a href="analisis-bivariable.html#cb260-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>()</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-147-1.png" width="672" /></p>
<p>Se aprecian comportamientos distintos para la edad en la respuesta pero se sugiere jugar con la transparencia de los gráficos para conocer mejor las distribuciones, simplemente se añade el parámetro <code>alpha</code>.</p>
<div class="sourceCode" id="cb261"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb261-1"><a href="analisis-bivariable.html#cb261-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb261-2"><a href="analisis-bivariable.html#cb261-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-148-1.png" width="672" /></p>
<p>Hay claramente dos distribuciones en función de la variable respuesta, estas distribuciones no son conocidas y tampoco es relevante porque es la distribución de la variable respuesta la que tiene importancia. La variable respuesta toma dos posibles valores y suponiendo cada cliente como independiente se tiene una distribución binomial como se ha indicado con anterioridad. Si el objetivo del ejercicio es establecer que características hacen que los clientes sean más propensos a adquirir un seguro de automóviles parece que la edad es una de esas características. A la vista del gráfico es más evidente que a mayor edad mayor interés, mayor probabilidad de adquirir un seguro de automóviles en la compañía. Cuando se tiene una variable respuesta es necesario estudiar esta variable frente a las variables que se consideren relevantes en su comportamiento, frente a todas las <strong>variables input</strong>. Por ejemplo, se repite el ejercicio contra <code>Vintage</code> que hace referencia a la antigüedad como cliente.</p>
<div class="sourceCode" id="cb262"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb262-1"><a href="analisis-bivariable.html#cb262-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Vintage, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb262-2"><a href="analisis-bivariable.html#cb262-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_density</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-149-1.png" width="672" /></p>
<p>En este caso la forma de la variable tanto para los que afirman estar interesados en el seguro de automóviles como para aquellos que no lo están es prácticamente la misma. De forma gráfica no parece que la antigüedad como cliente esté afectando a la variable respuesta. Para este tipo de análisis también se puede emplear el boxplot.</p>
<div class="sourceCode" id="cb263"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb263-1"><a href="analisis-bivariable.html#cb263-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Age, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb263-2"><a href="analisis-bivariable.html#cb263-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb263-3"><a href="analisis-bivariable.html#cb263-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb263-4"><a href="analisis-bivariable.html#cb263-4" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Vintage, <span class="at">group=</span><span class="fu">as.factor</span>(Response), <span class="at">fill=</span><span class="fu">as.factor</span>(Response))) <span class="sc">+</span> </span>
<span id="cb263-5"><a href="analisis-bivariable.html#cb263-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>(<span class="at">alpha =</span> <span class="fl">0.3</span>)</span>
<span id="cb263-6"><a href="analisis-bivariable.html#cb263-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb263-7"><a href="analisis-bivariable.html#cb263-7" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(p1,p2)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-150-1.png" width="672" /></p>
<p>Se aprecia como edades mayores muestran mayor propensión y como la antigüedad no está afectando al interés por el seguro de automóviles. Es importante reseñar que cualquier de los dos gráficos ofrece la forma, la distribución de las variables para cada nivel de la variable respuesta. Es necesario reseñar que en ningún momento aparece el número de observaciones ni se dispone de ningún mecanismo para identificar el peso que tiene cada grupo en estudio.</p>
<p>Como se ha indicado este análisis es necesario llevarlo a cabo con todas las variables input pero no es posible emplearlo cuando se comparan factores frente a factores, en esa situación es necesario emplear otro análisis gráfico.</p>
</div>
<div id="factores-frente-a-factores" class="section level2 hasAnchor" number="11.3">
<h2><span class="header-section-number">11.3</span> Factores frente a factores<a href="analisis-bivariable.html#factores-frente-a-factores" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En el capítulo 7 los factores se estudiaban mediante gráficos de barras y en el análisis bivariable se puede seguir la misma tónica pero será necesario apilar en la barra los niveles del otro factor en estudio para poder comparar. Se recomienda apilar el factor que haga de variable respuesta.</p>
<div class="sourceCode" id="cb264"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb264-1"><a href="analisis-bivariable.html#cb264-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Gender, <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb264-2"><a href="analisis-bivariable.html#cb264-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Gender, <span class="at">y=</span>clientes, <span class="at">fill=</span>target)) <span class="sc">+</span> </span>
<span id="cb264-3"><a href="analisis-bivariable.html#cb264-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-151-1.png" width="672" /></p>
<p>Es un gráfico apilado con un problema, no se puede determinar si el target es mayor para un sexo u otro, es necesario <strong>relativizar</strong>, es necesario estudiar los porcentajes de respuesta por nivel del factor input para no sacar conclusiones erróneas.</p>
<div class="sourceCode" id="cb265"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb265-1"><a href="analisis-bivariable.html#cb265-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Gender, <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb265-2"><a href="analisis-bivariable.html#cb265-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(target, <span class="at">pct_interesados =</span> clientes<span class="sc">/</span><span class="fu">sum</span>(clientes)) <span class="sc">%&gt;%</span> </span>
<span id="cb265-3"><a href="analisis-bivariable.html#cb265-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Gender, <span class="at">y=</span>pct_interesados, <span class="at">fill=</span>target)) <span class="sc">+</span> </span>
<span id="cb265-4"><a href="analisis-bivariable.html#cb265-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb265-5"><a href="analisis-bivariable.html#cb265-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">round</span>(pct_interesados,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="st">&#39;%&#39;</span>)), <span class="at">vjust=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-152-1.png" width="672" /></p>
<p>Al emplear % para comparar se pierde el número de observaciones pero facilita la comparación. Se van añadiendo posibilidades gráficas a ggplot, en este caso se incluyen los valores porcentuales mediante <code>geom_text</code> el ejemplo de uso no se complica mucho el código. También tiene interés en el anterior código el uso de <code>transmute</code> que permite crear porcentajes de grupos como una nueva variable a partir de <code>summarise</code>:</p>
<div class="sourceCode" id="cb266"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb266-1"><a href="analisis-bivariable.html#cb266-1" aria-hidden="true" tabindex="-1"></a><span class="fu">formattable</span>(train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Gender, <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span> </span>
<span id="cb266-2"><a href="analisis-bivariable.html#cb266-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb266-3"><a href="analisis-bivariable.html#cb266-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(target, <span class="at">pct_interesados =</span> <span class="fu">round</span>(clientes<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">sum</span>(clientes),<span class="dv">2</span>)))</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
Gender
</th>
<th style="text-align:right;">
target
</th>
<th style="text-align:right;">
pct_interesados
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
Female
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
89.61
</td>
</tr>
<tr>
<td style="text-align:right;">
Female
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
10.39
</td>
</tr>
<tr>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
86.16
</td>
</tr>
<tr>
<td style="text-align:right;">
Male
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
13.84
</td>
</tr>
</tbody>
</table>
<p>En el ejemplo de trabajo parece que los hombres encuestados muestran mayor interés por el producto de automóviles. Este mismo análisis se debe replicar para todos los factores input presentes en el conjunto de datos. Por ejemplo, la variable <code>Region_Code</code></p>
<div class="sourceCode" id="cb267"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb267-1"><a href="analisis-bivariable.html#cb267-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="at">Region =</span> <span class="fu">as.factor</span>(Region_Code), <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span> </span>
<span id="cb267-2"><a href="analisis-bivariable.html#cb267-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb267-3"><a href="analisis-bivariable.html#cb267-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(target, <span class="at">pct_interesados =</span> clientes<span class="sc">/</span><span class="fu">sum</span>(clientes)) <span class="sc">%&gt;%</span> </span>
<span id="cb267-4"><a href="analisis-bivariable.html#cb267-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Region, <span class="at">y=</span>pct_interesados, <span class="at">fill=</span>target)) <span class="sc">+</span> </span>
<span id="cb267-5"><a href="analisis-bivariable.html#cb267-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb267-6"><a href="analisis-bivariable.html#cb267-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">round</span>(pct_interesados,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="st">&#39;%&#39;</span>)), <span class="at">vjust=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-154-1.png" width="672" /></p>
<p>En este gráfico aparecen dos problemas que el científico de datos tiene que tener en cuenta cuando trabaje con factores.</p>
<ul>
<li>El factor tiene demasiados niveles</li>
<li>El factor puede tener pocas observaciones y se están sacando conclusiones con pocos registros</li>
</ul>
<p>Al primer problema ya se hizo mención al inicio del ensayo, se sugiere realizar una agrupación de niveles para facilitar su interpretación. Además, es posible que se obtengan conclusiones sobre niveles del factor que puedan llevar al error debido a la escasa <strong>prevalencia</strong>. La prevalencia tiene diversas definiciones pero en este caso se define como el divisor en el cálculo del porcentaje dentro del nivel del factor.</p>
<p><span class="math display">\[pct-interesados_{nivel-i}= \frac {interesados_{nivel-i}}{observaciones_{nivel-i}} = \frac {interesados_{nivel-i}}{prevalencia_{nivel-i}}\]</span></p>
<p>Es relevante porque es <strong>sentido común</strong> no dar el mismo valor al % de la variable respuesta en una provincia donde se tiene una cartera de 80.000 clientes que en una provincia donde se tienen 80 clientes. El % de clientes interesados en un caso se calcula con un denominador de 80.000 y en otro caso con un denominador de 80 y <strong>en los gráficos presentados hasta el momento no es posible estudiar correctamente la prevalencia</strong>.</p>
<p>Cuando el científico de datos se encuentre situaciones de baja prevalencia o alto número de niveles de un factor ha de pensar una estrategia para abordar el problema. Siempre se debe priorizar la realización de “agrupaciones con sentido de negocio”. En este caso, si se conoce la división territorial, agrupar por comunidades autónomas, por zonas, territoriales o separar las provincias más relevantes frente al resto. Por ejemplo:</p>
<div class="sourceCode" id="cb268"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb268-1"><a href="analisis-bivariable.html#cb268-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">fr_region =</span> <span class="fu">case_when</span>(</span>
<span id="cb268-2"><a href="analisis-bivariable.html#cb268-2" aria-hidden="true" tabindex="-1"></a>  Region_Code <span class="sc">==</span> <span class="dv">8</span> <span class="sc">~</span> <span class="st">&#39;Barcelona&#39;</span>,</span>
<span id="cb268-3"><a href="analisis-bivariable.html#cb268-3" aria-hidden="true" tabindex="-1"></a>  Region_Code <span class="sc">==</span> <span class="dv">28</span> <span class="sc">~</span> <span class="st">&#39;Madrid&#39;</span>,</span>
<span id="cb268-4"><a href="analisis-bivariable.html#cb268-4" aria-hidden="true" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;Resto&#39;</span>))</span>
<span id="cb268-5"><a href="analisis-bivariable.html#cb268-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb268-6"><a href="analisis-bivariable.html#cb268-6" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="at">Region =</span> <span class="fu">as.factor</span>(fr_region), <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span> <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb268-7"><a href="analisis-bivariable.html#cb268-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(target, <span class="at">pct_interesados =</span> clientes<span class="sc">/</span><span class="fu">sum</span>(clientes)) <span class="sc">%&gt;%</span> </span>
<span id="cb268-8"><a href="analisis-bivariable.html#cb268-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Region, <span class="at">y=</span>pct_interesados, <span class="at">fill=</span>target)) <span class="sc">+</span> </span>
<span id="cb268-9"><a href="analisis-bivariable.html#cb268-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb268-10"><a href="analisis-bivariable.html#cb268-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">round</span>(pct_interesados,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="st">&#39;%&#39;</span>)), <span class="at">vjust=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-155-1.png" width="672" /></p>
<blockquote>
<p>Se sugiere que aquellas variables del conjunto de datos que estén analizadas o clasificadas empiecen por un prefijo o se las pueda distinguir de algún modo dentro del tablón de datos, en este caso y a lo largo de todo el trabajo, se emplea el prefijo <strong>fr_</strong> para indicar <strong>f</strong>actor <strong>r</strong>eclasificado. Esto facilitará la automatización de análisis y los procesos de modelización como se verá con posterioridad.</p>
</blockquote>
<p>Parece más alto el interés en Madrid, sin embargo, el % de interesados en Barcelona y el resto de España es similar. No es una agrupación convincente pero puede interesar a un equipo de negocio. Otro mecanismo de unión de factores puede basarse en la propia variable respuesta, que sea ese % el que agrupe la variable. A continuación se plantea una agrupación en buenos, regulares y malos, agrupación de niveles de un factor simplista basada en el % de respuesta.</p>
<div class="sourceCode" id="cb269"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb269-1"><a href="analisis-bivariable.html#cb269-1" aria-hidden="true" tabindex="-1"></a>res <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(Region_Code) <span class="sc">%&gt;%</span> </span>
<span id="cb269-2"><a href="analisis-bivariable.html#cb269-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>(), <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(Response)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">2</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb269-3"><a href="analisis-bivariable.html#cb269-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_interesados)) <span class="sc">%&gt;%</span> </span>
<span id="cb269-4"><a href="analisis-bivariable.html#cb269-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_agregado_clientes =</span> <span class="fu">cumsum</span>(clientes)<span class="sc">/</span><span class="fu">nrow</span>(train),</span>
<span id="cb269-5"><a href="analisis-bivariable.html#cb269-5" aria-hidden="true" tabindex="-1"></a>         <span class="at">pct_anterior_agregado=</span><span class="fu">lag</span>(pct_agregado_clientes, <span class="at">default =</span> <span class="dv">0</span>))</span>
<span id="cb269-6"><a href="analisis-bivariable.html#cb269-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb269-7"><a href="analisis-bivariable.html#cb269-7" aria-hidden="true" tabindex="-1"></a><span class="fu">formattable</span>(res, <span class="at">digits=</span><span class="dv">2</span>, <span class="fu">list</span>(<span class="at">pct_interesados=</span><span class="fu">color_bar</span>(<span class="st">&#39;grey&#39;</span>)))</span></code></pre></div>
<table class="table table-condensed">
<thead>
<tr>
<th style="text-align:right;">
Region_Code
</th>
<th style="text-align:right;">
clientes
</th>
<th style="text-align:right;">
pct_interesados
</th>
<th style="text-align:right;">
pct_agregado_clientes
</th>
<th style="text-align:right;">
pct_anterior_agregado
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
38
</td>
<td style="text-align:right;">
2026
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 100.00%">19.2</span>
</td>
<td style="text-align:right;">
0.0053
</td>
<td style="text-align:right;">
0.0000
</td>
</tr>
<tr>
<td style="text-align:right;">
28
</td>
<td style="text-align:right;">
106415
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 97.50%">18.7</span>
</td>
<td style="text-align:right;">
0.2845
</td>
<td style="text-align:right;">
0.0053
</td>
</tr>
<tr>
<td style="text-align:right;">
19
</td>
<td style="text-align:right;">
1535
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 84.84%">16.3</span>
</td>
<td style="text-align:right;">
0.2886
</td>
<td style="text-align:right;">
0.2845
</td>
</tr>
<tr>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1801
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 82.40%">15.8</span>
</td>
<td style="text-align:right;">
0.2933
</td>
<td style="text-align:right;">
0.2886
</td>
</tr>
<tr>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
1960
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 79.74%">15.3</span>
</td>
<td style="text-align:right;">
0.2984
</td>
<td style="text-align:right;">
0.2933
</td>
</tr>
<tr>
<td style="text-align:right;">
51
</td>
<td style="text-align:right;">
183
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 79.69%">15.3</span>
</td>
<td style="text-align:right;">
0.2989
</td>
<td style="text-align:right;">
0.2984
</td>
</tr>
<tr>
<td style="text-align:right;">
24
</td>
<td style="text-align:right;">
2415
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 73.75%">14.2</span>
</td>
<td style="text-align:right;">
0.3053
</td>
<td style="text-align:right;">
0.2989
</td>
</tr>
<tr>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
3279
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 68.59%">13.2</span>
</td>
<td style="text-align:right;">
0.3139
</td>
<td style="text-align:right;">
0.3053
</td>
</tr>
<tr>
<td style="text-align:right;">
18
</td>
<td style="text-align:right;">
5153
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 68.54%">13.2</span>
</td>
<td style="text-align:right;">
0.3274
</td>
<td style="text-align:right;">
0.3139
</td>
</tr>
<tr>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
9251
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 66.51%">12.8</span>
</td>
<td style="text-align:right;">
0.3517
</td>
<td style="text-align:right;">
0.3274
</td>
</tr>
<tr>
<td style="text-align:right;">
35
</td>
<td style="text-align:right;">
6942
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 64.90%">12.5</span>
</td>
<td style="text-align:right;">
0.3699
</td>
<td style="text-align:right;">
0.3517
</td>
</tr>
<tr>
<td style="text-align:right;">
39
</td>
<td style="text-align:right;">
4644
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 64.38%">12.4</span>
</td>
<td style="text-align:right;">
0.3821
</td>
<td style="text-align:right;">
0.3699
</td>
</tr>
<tr>
<td style="text-align:right;">
52
</td>
<td style="text-align:right;">
267
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 64.38%">12.4</span>
</td>
<td style="text-align:right;">
0.3828
</td>
<td style="text-align:right;">
0.3821
</td>
</tr>
<tr>
<td style="text-align:right;">
29
</td>
<td style="text-align:right;">
11065
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 64.27%">12.3</span>
</td>
<td style="text-align:right;">
0.4118
</td>
<td style="text-align:right;">
0.3828
</td>
</tr>
<tr>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
18263
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 63.44%">12.2</span>
</td>
<td style="text-align:right;">
0.4597
</td>
<td style="text-align:right;">
0.4118
</td>
</tr>
<tr>
<td style="text-align:right;">
40
</td>
<td style="text-align:right;">
1295
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 61.51%">11.8</span>
</td>
<td style="text-align:right;">
0.4631
</td>
<td style="text-align:right;">
0.4597
</td>
</tr>
<tr>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
1279
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 60.26%">11.6</span>
</td>
<td style="text-align:right;">
0.4665
</td>
<td style="text-align:right;">
0.4631
</td>
</tr>
<tr>
<td style="text-align:right;">
20
</td>
<td style="text-align:right;">
1935
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 60.00%">11.5</span>
</td>
<td style="text-align:right;">
0.4715
</td>
<td style="text-align:right;">
0.4665
</td>
</tr>
<tr>
<td style="text-align:right;">
11
</td>
<td style="text-align:right;">
9232
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 58.75%">11.3</span>
</td>
<td style="text-align:right;">
0.4958
</td>
<td style="text-align:right;">
0.4715
</td>
</tr>
<tr>
<td style="text-align:right;">
45
</td>
<td style="text-align:right;">
5605
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 57.14%">11.0</span>
</td>
<td style="text-align:right;">
0.5105
</td>
<td style="text-align:right;">
0.4958
</td>
</tr>
<tr>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1008
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 56.30%">10.8</span>
</td>
<td style="text-align:right;">
0.5131
</td>
<td style="text-align:right;">
0.5105
</td>
</tr>
<tr>
<td style="text-align:right;">
46
</td>
<td style="text-align:right;">
19749
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 53.59%">10.3</span>
</td>
<td style="text-align:right;">
0.5649
</td>
<td style="text-align:right;">
0.5131
</td>
</tr>
<tr>
<td style="text-align:right;">
48
</td>
<td style="text-align:right;">
4681
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 53.07%">10.2</span>
</td>
<td style="text-align:right;">
0.5772
</td>
<td style="text-align:right;">
0.5649
</td>
</tr>
<tr>
<td style="text-align:right;">
31
</td>
<td style="text-align:right;">
1960
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 52.34%">10.1</span>
</td>
<td style="text-align:right;">
0.5824
</td>
<td style="text-align:right;">
0.5772
</td>
</tr>
<tr>
<td style="text-align:right;">
33
</td>
<td style="text-align:right;">
7654
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 51.72%">9.9</span>
</td>
<td style="text-align:right;">
0.6024
</td>
<td style="text-align:right;">
0.5824
</td>
</tr>
<tr>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
3198
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 50.83%">9.8</span>
</td>
<td style="text-align:right;">
0.6108
</td>
<td style="text-align:right;">
0.6024
</td>
</tr>
<tr>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
33877
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 50.05%">9.6</span>
</td>
<td style="text-align:right;">
0.6997
</td>
<td style="text-align:right;">
0.6108
</td>
</tr>
<tr>
<td style="text-align:right;">
43
</td>
<td style="text-align:right;">
2639
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 48.18%">9.2</span>
</td>
<td style="text-align:right;">
0.7067
</td>
<td style="text-align:right;">
0.6997
</td>
</tr>
<tr>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
4036
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 46.98%">9.0</span>
</td>
<td style="text-align:right;">
0.7172
</td>
<td style="text-align:right;">
0.7067
</td>
</tr>
<tr>
<td style="text-align:right;">
14
</td>
<td style="text-align:right;">
4678
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 46.98%">9.0</span>
</td>
<td style="text-align:right;">
0.7295
</td>
<td style="text-align:right;">
0.7172
</td>
</tr>
<tr>
<td style="text-align:right;">
47
</td>
<td style="text-align:right;">
7436
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 45.68%">8.8</span>
</td>
<td style="text-align:right;">
0.7490
</td>
<td style="text-align:right;">
0.7295
</td>
</tr>
<tr>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2021
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 44.84%">8.6</span>
</td>
<td style="text-align:right;">
0.7543
</td>
<td style="text-align:right;">
0.7490
</td>
</tr>
<tr>
<td style="text-align:right;">
32
</td>
<td style="text-align:right;">
2787
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 44.69%">8.6</span>
</td>
<td style="text-align:right;">
0.7616
</td>
<td style="text-align:right;">
0.7543
</td>
</tr>
<tr>
<td style="text-align:right;">
9
</td>
<td style="text-align:right;">
3101
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 42.50%">8.2</span>
</td>
<td style="text-align:right;">
0.7698
</td>
<td style="text-align:right;">
0.7616
</td>
</tr>
<tr>
<td style="text-align:right;">
36
</td>
<td style="text-align:right;">
8797
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 41.61%">8.0</span>
</td>
<td style="text-align:right;">
0.7929
</td>
<td style="text-align:right;">
0.7698
</td>
</tr>
<tr>
<td style="text-align:right;">
37
</td>
<td style="text-align:right;">
5501
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 41.30%">7.9</span>
</td>
<td style="text-align:right;">
0.8073
</td>
<td style="text-align:right;">
0.7929
</td>
</tr>
<tr>
<td style="text-align:right;">
34
</td>
<td style="text-align:right;">
1664
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 39.43%">7.6</span>
</td>
<td style="text-align:right;">
0.8117
</td>
<td style="text-align:right;">
0.8073
</td>
</tr>
<tr>
<td style="text-align:right;">
49
</td>
<td style="text-align:right;">
1832
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 38.96%">7.5</span>
</td>
<td style="text-align:right;">
0.8165
</td>
<td style="text-align:right;">
0.8117
</td>
</tr>
<tr>
<td style="text-align:right;">
42
</td>
<td style="text-align:right;">
591
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 38.80%">7.4</span>
</td>
<td style="text-align:right;">
0.8180
</td>
<td style="text-align:right;">
0.8165
</td>
</tr>
<tr>
<td style="text-align:right;">
27
</td>
<td style="text-align:right;">
2823
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 38.54%">7.4</span>
</td>
<td style="text-align:right;">
0.8254
</td>
<td style="text-align:right;">
0.8180
</td>
</tr>
<tr>
<td style="text-align:right;">
30
</td>
<td style="text-align:right;">
12191
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 38.44%">7.4</span>
</td>
<td style="text-align:right;">
0.8574
</td>
<td style="text-align:right;">
0.8254
</td>
</tr>
<tr>
<td style="text-align:right;">
26
</td>
<td style="text-align:right;">
2587
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 37.66%">7.2</span>
</td>
<td style="text-align:right;">
0.8642
</td>
<td style="text-align:right;">
0.8574
</td>
</tr>
<tr>
<td style="text-align:right;">
15
</td>
<td style="text-align:right;">
13308
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 37.50%">7.2</span>
</td>
<td style="text-align:right;">
0.8991
</td>
<td style="text-align:right;">
0.8642
</td>
</tr>
<tr>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
4038
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 37.03%">7.1</span>
</td>
<td style="text-align:right;">
0.9097
</td>
<td style="text-align:right;">
0.8991
</td>
</tr>
<tr>
<td style="text-align:right;">
21
</td>
<td style="text-align:right;">
4266
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 36.98%">7.1</span>
</td>
<td style="text-align:right;">
0.9209
</td>
<td style="text-align:right;">
0.9097
</td>
</tr>
<tr>
<td style="text-align:right;">
17
</td>
<td style="text-align:right;">
2617
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 36.61%">7.0</span>
</td>
<td style="text-align:right;">
0.9278
</td>
<td style="text-align:right;">
0.9209
</td>
</tr>
<tr>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
6280
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 36.41%">7.0</span>
</td>
<td style="text-align:right;">
0.9443
</td>
<td style="text-align:right;">
0.9278
</td>
</tr>
<tr>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
2007
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 34.79%">6.7</span>
</td>
<td style="text-align:right;">
0.9495
</td>
<td style="text-align:right;">
0.9443
</td>
</tr>
<tr>
<td style="text-align:right;">
22
</td>
<td style="text-align:right;">
1309
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 33.02%">6.3</span>
</td>
<td style="text-align:right;">
0.9530
</td>
<td style="text-align:right;">
0.9495
</td>
</tr>
<tr>
<td style="text-align:right;">
50
</td>
<td style="text-align:right;">
10243
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 32.66%">6.3</span>
</td>
<td style="text-align:right;">
0.9798
</td>
<td style="text-align:right;">
0.9530
</td>
</tr>
<tr>
<td style="text-align:right;">
10
</td>
<td style="text-align:right;">
4374
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 31.30%">6.0</span>
</td>
<td style="text-align:right;">
0.9913
</td>
<td style="text-align:right;">
0.9798
</td>
</tr>
<tr>
<td style="text-align:right;">
25
</td>
<td style="text-align:right;">
2503
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 22.24%">4.3</span>
</td>
<td style="text-align:right;">
0.9979
</td>
<td style="text-align:right;">
0.9913
</td>
</tr>
<tr>
<td style="text-align:right;">
44
</td>
<td style="text-align:right;">
808
</td>
<td style="text-align:right;">
<span style="display: inline-block; direction: rtl; unicode-bidi: plaintext; border-radius: 4px; padding-right: 2px; background-color: grey; width: 21.25%">4.1</span>
</td>
<td style="text-align:right;">
1.0000
</td>
<td style="text-align:right;">
0.9979
</td>
</tr>
</tbody>
</table>
<p>La librería <code>formattable</code> además de permitir presentar de forma elegante data frames, puede añadir mayor vistosidad a las tablas como ilustra el ejemplo. Para facilitar el análisis se suma la variable <code>Response</code>, motivo por el cual no se transforma (aun) en factor, en ocasiones facilita el trabajo mantenerla como numérica. Se crea un <code>agregado_clientes</code> para determinar el % de clientes que se van agrupando. Mediante la función <code>lag</code> que permite extraer el anterior registro de un data frame se busca si la acumulación de clientes de la anterior región ya ha superado el 10% de las observaciones, de esa forma se crean grupos de provincias en función de la tasa de respuesta.</p>
<p>La primera agrupación de provincias será aquella que supere el 10% de las observaciones.</p>
<div class="sourceCode" id="cb270"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb270-1"><a href="analisis-bivariable.html#cb270-1" aria-hidden="true" tabindex="-1"></a>muy_buenos <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="st">&quot;1 muy buenos&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb270-2"><a href="analisis-bivariable.html#cb270-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pct_anterior_agregado<span class="sc">&lt;</span><span class="fl">0.1</span>)</span></code></pre></div>
<p>Se vuelve a recalcular el agregado de clientes eliminando las provincias ya clasificadas y el siguiente corte se establece cuando se supere otro 10% de observaciones.</p>
<div class="sourceCode" id="cb271"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb271-1"><a href="analisis-bivariable.html#cb271-1" aria-hidden="true" tabindex="-1"></a>buenos <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(muy_buenos<span class="sc">$</span>Region_Code))) <span class="sc">%&gt;%</span> </span>
<span id="cb271-2"><a href="analisis-bivariable.html#cb271-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_agregado_clientes =</span> <span class="fu">cumsum</span>(clientes)<span class="sc">/</span><span class="fu">nrow</span>(train),</span>
<span id="cb271-3"><a href="analisis-bivariable.html#cb271-3" aria-hidden="true" tabindex="-1"></a>         <span class="at">pct_anterior_agregado=</span><span class="fu">lag</span>(pct_agregado_clientes, <span class="at">default =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="st">&quot;2 buenos&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb271-4"><a href="analisis-bivariable.html#cb271-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pct_anterior_agregado<span class="sc">&lt;</span><span class="fl">0.1</span>)</span></code></pre></div>
<p>Este proceso se plantea de forma iterativa en distintos data frames para entender el proceso y así se crean los grupos <em>muy bueno, bueno, regular, malo, muy malo</em> de provincias en base a la variable target.</p>
<div class="sourceCode" id="cb272"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb272-1"><a href="analisis-bivariable.html#cb272-1" aria-hidden="true" tabindex="-1"></a>regulares <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(muy_buenos<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span> </span>
<span id="cb272-2"><a href="analisis-bivariable.html#cb272-2" aria-hidden="true" tabindex="-1"></a>                            <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(buenos<span class="sc">$</span>Region_Code))) <span class="sc">%&gt;%</span> </span>
<span id="cb272-3"><a href="analisis-bivariable.html#cb272-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_agregado_clientes =</span> <span class="fu">cumsum</span>(clientes)<span class="sc">/</span><span class="fu">nrow</span>(train),</span>
<span id="cb272-4"><a href="analisis-bivariable.html#cb272-4" aria-hidden="true" tabindex="-1"></a>         <span class="at">pct_anterior_agregado=</span><span class="fu">lag</span>(pct_agregado_clientes, <span class="at">default =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="st">&quot;3 regulares&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb272-5"><a href="analisis-bivariable.html#cb272-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pct_anterior_agregado<span class="sc">&lt;</span><span class="fl">0.1</span>)</span>
<span id="cb272-6"><a href="analisis-bivariable.html#cb272-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-7"><a href="analisis-bivariable.html#cb272-7" aria-hidden="true" tabindex="-1"></a>malos <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(muy_buenos<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span> </span>
<span id="cb272-8"><a href="analisis-bivariable.html#cb272-8" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(buenos<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span></span>
<span id="cb272-9"><a href="analisis-bivariable.html#cb272-9" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(regulares<span class="sc">$</span>Region_Code))) <span class="sc">%&gt;%</span> </span>
<span id="cb272-10"><a href="analisis-bivariable.html#cb272-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">pct_agregado_clientes =</span> <span class="fu">cumsum</span>(clientes)<span class="sc">/</span><span class="fu">nrow</span>(train),</span>
<span id="cb272-11"><a href="analisis-bivariable.html#cb272-11" aria-hidden="true" tabindex="-1"></a>         <span class="at">pct_anterior_agregado=</span><span class="fu">lag</span>(pct_agregado_clientes, <span class="at">default =</span> <span class="dv">0</span>)) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="st">&quot;4 malos&quot;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb272-12"><a href="analisis-bivariable.html#cb272-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(pct_anterior_agregado<span class="sc">&lt;</span><span class="fl">0.1</span>)</span>
<span id="cb272-13"><a href="analisis-bivariable.html#cb272-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-14"><a href="analisis-bivariable.html#cb272-14" aria-hidden="true" tabindex="-1"></a>muy_malos <span class="ot">&lt;-</span> res <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(muy_buenos<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span> </span>
<span id="cb272-15"><a href="analisis-bivariable.html#cb272-15" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(buenos<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span></span>
<span id="cb272-16"><a href="analisis-bivariable.html#cb272-16" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(regulares<span class="sc">$</span>Region_Code)) <span class="sc">&amp;</span></span>
<span id="cb272-17"><a href="analisis-bivariable.html#cb272-17" aria-hidden="true" tabindex="-1"></a>                        <span class="sc">!</span>(Region_Code <span class="sc">%in%</span> <span class="fu">unique</span>(malos<span class="sc">$</span>Region_Code))) <span class="sc">%&gt;%</span> </span>
<span id="cb272-18"><a href="analisis-bivariable.html#cb272-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">grupo =</span> <span class="st">&quot;5 muy_malos&quot;</span>)</span>
<span id="cb272-19"><a href="analisis-bivariable.html#cb272-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-20"><a href="analisis-bivariable.html#cb272-20" aria-hidden="true" tabindex="-1"></a>grupos_region <span class="ot">&lt;-</span> <span class="fu">rbind.data.frame</span>(muy_buenos, buenos, regulares, malos, muy_malos) <span class="sc">%&gt;%</span> </span>
<span id="cb272-21"><a href="analisis-bivariable.html#cb272-21" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fr_region2 =</span> grupo) <span class="sc">%&gt;%</span> <span class="fu">select</span>(Region_Code, fr_region2)</span>
<span id="cb272-22"><a href="analisis-bivariable.html#cb272-22" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb272-23"><a href="analisis-bivariable.html#cb272-23" aria-hidden="true" tabindex="-1"></a><span class="fu">remove</span>(res, muy_buenos, buenos, regulares, malos, muy_malos)</span></code></pre></div>
<p>Es útil ver paso a paso que regiones se van uniendo por si existe algún criterio de negocio o se encuentra algún indicador que pueda mejorar esta agrupación ya que este trabajo no tiene ningún sentido práctico más allá de unir regiones con similares tasas de respuesta, al científico de datos puede interesarle llevar estos datos a una hoja de cálculo y realizar sus propias agrupaciones. Si se trabaja con un gran número de variables existen librerías en R que realizan esta labor de forma automática tanto con variables numéricas como con factores pero se recomienda controlar como se producen estas agrupaciones.</p>
<p>Ya se dispone de un data frame auxiliar que es necesario unir al tablón de trabajo.</p>
<div class="sourceCode" id="cb273"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb273-1"><a href="analisis-bivariable.html#cb273-1" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(grupos_region)</span></code></pre></div>
<pre><code>## Joining, by = &quot;Region_Code&quot;</code></pre>
<p>Se repite el gráfico de barras apiladas.</p>
<div class="sourceCode" id="cb275"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb275-1"><a href="analisis-bivariable.html#cb275-1" aria-hidden="true" tabindex="-1"></a>train <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(<span class="at">Region =</span> <span class="fu">as.factor</span>(fr_region2), <span class="at">target=</span><span class="fu">as.factor</span>(Response)) <span class="sc">%&gt;%</span>    </span>
<span id="cb275-2"><a href="analisis-bivariable.html#cb275-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">clientes=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb275-3"><a href="analisis-bivariable.html#cb275-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">transmute</span>(target, <span class="at">pct_interesados =</span> clientes<span class="sc">/</span><span class="fu">sum</span>(clientes)) <span class="sc">%&gt;%</span> </span>
<span id="cb275-4"><a href="analisis-bivariable.html#cb275-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>Region, <span class="at">y=</span>pct_interesados, <span class="at">fill=</span>target)) <span class="sc">+</span> </span>
<span id="cb275-5"><a href="analisis-bivariable.html#cb275-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_bar</span>(<span class="at">stat=</span><span class="st">&quot;identity&quot;</span>) <span class="sc">+</span> </span>
<span id="cb275-6"><a href="analisis-bivariable.html#cb275-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">label=</span><span class="fu">paste0</span>(<span class="fu">round</span>(pct_interesados,<span class="dv">4</span>)<span class="sc">*</span><span class="dv">100</span>,<span class="st">&#39;%&#39;</span>)), <span class="at">vjust=</span><span class="dv">0</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-161-1.png" width="672" /></p>
<p>Para facilitar la labor y no trabajar con recodificación de factores se opta por numerar cada nivel del factor algo que ayuda en las visualizaciones, es necesario recordar que hay factores con orden (como es el caso). La agrupación de provincias garantiza que tiene en cada nivel al menos un 10% de observaciones, además parece que esa agrupación discrimina la variable respuesta, pero este análisis gráfico es claramente mejorable.</p>
</div>
<div id="propuesta-de-análisis-gráfico-para-el-análisis-bivariable" class="section level2 hasAnchor" number="11.4">
<h2><span class="header-section-number">11.4</span> Propuesta de análisis gráfico para el análisis bivariable<a href="analisis-bivariable.html#propuesta-de-análisis-gráfico-para-el-análisis-bivariable" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El científico de datos ha de elaborar sus propias herramientas y sus propias funciones gráficas para mostrar estos análisis iniciales sobre sus datos. Estas aproximaciones son fundamentales para el trabajo de documentación y modelización y en ocasiones el científico de datos tendrá que exponer estos resultados previos a equipos que no están familiarizados con la visualización de datos. Por este motivo, una buena o mala visualización no la establece la literatura sobre la realización de gráficos, la establece la capacidad de comprensión que tengan las áreas usuarias de las visualizaciones.</p>
<p>En este caso se propone un análisis gráfico de uso en el ámbito actuarial donde la ciencia de datos tiene múltiples casos de éxito. Se trata de un gráfico de doble eje y donde el eje y de la izquierda representará el % de observaciones del nivel del factor (prevalencia) y permitirá dar un peso a la información que suministra ese nivel del factor. En el eje y de la derecha se pondrá la proporción, la tasa de respuesta del target en estudio.</p>
<div class="sourceCode" id="cb276"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb276-1"><a href="analisis-bivariable.html#cb276-1" aria-hidden="true" tabindex="-1"></a>resumen <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb276-2"><a href="analisis-bivariable.html#cb276-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">factor_analisis =</span> Age) <span class="sc">%&gt;%</span></span>
<span id="cb276-3"><a href="analisis-bivariable.html#cb276-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">pct_clientes =</span> <span class="fu">round</span>(<span class="fu">n</span>()<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">nrow</span>(train),<span class="dv">1</span>),</span>
<span id="cb276-4"><a href="analisis-bivariable.html#cb276-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(Response)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">1</span>), <span class="at">.groups=</span><span class="st">&#39;drop&#39;</span>)</span>
<span id="cb276-5"><a href="analisis-bivariable.html#cb276-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb276-6"><a href="analisis-bivariable.html#cb276-6" aria-hidden="true" tabindex="-1"></a>ajuste <span class="ot">=</span> <span class="dv">1</span></span>
<span id="cb276-7"><a href="analisis-bivariable.html#cb276-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb276-8"><a href="analisis-bivariable.html#cb276-8" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resumen, <span class="fu">aes</span>(<span class="at">x=</span>factor_analisis)) <span class="sc">+</span></span>
<span id="cb276-9"><a href="analisis-bivariable.html#cb276-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste), <span class="at">group=</span><span class="dv">1</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb276-10"><a href="analisis-bivariable.html#cb276-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_clientes),<span class="at">fill=</span><span class="st">&quot;yellow&quot;</span>,<span class="at">alpha=</span><span class="fl">0.5</span>)  <span class="sc">+</span></span>
<span id="cb276-11"><a href="analisis-bivariable.html#cb276-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste, <span class="at">label =</span> <span class="fu">paste</span>(pct_interesados,<span class="st">&#39; %&#39;</span>)), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb276-12"><a href="analisis-bivariable.html#cb276-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span>.<span class="sc">/</span>ajuste, <span class="at">name=</span><span class="st">&quot;% interesados&quot;</span>), <span class="at">name=</span><span class="st">&#39;% clientes&#39;</span>) <span class="sc">+</span></span>
<span id="cb276-13"><a href="analisis-bivariable.html#cb276-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb276-14"><a href="analisis-bivariable.html#cb276-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb276-15"><a href="analisis-bivariable.html#cb276-15" aria-hidden="true" tabindex="-1"></a>g2 <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Análisis de la variable edad&quot;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-162-1.png" width="672" /></p>
<p>Tabularmente sería complejo de ver al tener un gran número de niveles, pero el gráfico permite estudiar como se distribuye la población para cada nivel del factor y como es su comportamiento frente a la variable target. En este caso ggplot representa en forma de línea continua la tasa de respuesta (<code>geom_line</code>) y en barra el % de observaciones (<code>geom_col</code>), se añade el valor del % de clientes interesados mediante <code>geom_text</code> mejorando el formato y es <code>scale_y_continuous</code> junto con <code>sec_axis</code> lo que permite crear un gráfico de doble eje a ggplot. Pero es necesario que ambos ejes estén en la misma escala, por eso se añade un ajuste en <code>sec_axis</code>. En el anterior gráfico se aprecia que pasa si se deja ese ajuste a 1, para mejorar la visualización se puede jugar con ese ajuste para el eje y de la derecha.</p>
<div class="sourceCode" id="cb277"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb277-1"><a href="analisis-bivariable.html#cb277-1" aria-hidden="true" tabindex="-1"></a>resumen <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span></span>
<span id="cb277-2"><a href="analisis-bivariable.html#cb277-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(<span class="at">factor_analisis =</span> Age) <span class="sc">%&gt;%</span></span>
<span id="cb277-3"><a href="analisis-bivariable.html#cb277-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">pct_clientes =</span> <span class="fu">round</span>(<span class="fu">n</span>()<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">nrow</span>(train),<span class="dv">1</span>),</span>
<span id="cb277-4"><a href="analisis-bivariable.html#cb277-4" aria-hidden="true" tabindex="-1"></a>            <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(Response)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">1</span>), <span class="at">.groups=</span><span class="st">&#39;drop&#39;</span>)</span>
<span id="cb277-5"><a href="analisis-bivariable.html#cb277-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb277-6"><a href="analisis-bivariable.html#cb277-6" aria-hidden="true" tabindex="-1"></a>ajuste <span class="ot">=</span> <span class="fl">0.5</span></span>
<span id="cb277-7"><a href="analisis-bivariable.html#cb277-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb277-8"><a href="analisis-bivariable.html#cb277-8" aria-hidden="true" tabindex="-1"></a>g2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(resumen, <span class="fu">aes</span>(<span class="at">x=</span>factor_analisis)) <span class="sc">+</span></span>
<span id="cb277-9"><a href="analisis-bivariable.html#cb277-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste), <span class="at">group=</span><span class="dv">1</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb277-10"><a href="analisis-bivariable.html#cb277-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_clientes),<span class="at">fill=</span><span class="st">&quot;yellow&quot;</span>,<span class="at">alpha=</span><span class="fl">0.5</span>)  <span class="sc">+</span></span>
<span id="cb277-11"><a href="analisis-bivariable.html#cb277-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_text</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste, <span class="at">label =</span> <span class="fu">paste</span>(pct_interesados,<span class="st">&#39; %&#39;</span>)), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb277-12"><a href="analisis-bivariable.html#cb277-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">scale_y_continuous</span>(<span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span>.<span class="sc">/</span>ajuste, <span class="at">name=</span><span class="st">&quot;% interesados&quot;</span>), <span class="at">name=</span><span class="st">&#39;% clientes&#39;</span>) <span class="sc">+</span></span>
<span id="cb277-13"><a href="analisis-bivariable.html#cb277-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme_light</span>()</span>
<span id="cb277-14"><a href="analisis-bivariable.html#cb277-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb277-15"><a href="analisis-bivariable.html#cb277-15" aria-hidden="true" tabindex="-1"></a>g2 <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="st">&quot;Análisis de la variable edad&quot;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-163-1.png" width="672" /></p>
<p>Se aprecia como el eje y de la izquierda es la mitad del eje y de la derecha, se produce un ajuste del 0.5. Los clientes encuestados son mayoritariamente jóvenes entre 24-30 años que no muestran interés en el producto, sin embargo, hay una serie de clientes entre 35 y 50 años que sí tienen interés, a medida que se avanza en la edad ese mismo interés en el producto de automóviles va cayendo.</p>
<p>Entendido este gráfico habría de ser replicado para todos los factores presentes en el análisis, cuando se repita un código en múltiples ocasiones es recomendable crear una función.</p>
<div class="sourceCode" id="cb278"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb278-1"><a href="analisis-bivariable.html#cb278-1" aria-hidden="true" tabindex="-1"></a>bivariable <span class="ot">&lt;-</span> <span class="cf">function</span>(df, target, varib, <span class="at">ajuste=</span><span class="dv">1</span>){</span>
<span id="cb278-2"><a href="analisis-bivariable.html#cb278-2" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb278-3"><a href="analisis-bivariable.html#cb278-3" aria-hidden="true" tabindex="-1"></a>target <span class="ot">=</span> <span class="fu">as.symbol</span>(target)</span>
<span id="cb278-4"><a href="analisis-bivariable.html#cb278-4" aria-hidden="true" tabindex="-1"></a>fr_analisis <span class="ot">=</span> <span class="fu">as.symbol</span>(varib)</span>
<span id="cb278-5"><a href="analisis-bivariable.html#cb278-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb278-6"><a href="analisis-bivariable.html#cb278-6" aria-hidden="true" tabindex="-1"></a>g <span class="ot">&lt;-</span> df <span class="sc">%&gt;%</span></span>
<span id="cb278-7"><a href="analisis-bivariable.html#cb278-7" aria-hidden="true" tabindex="-1"></a>   <span class="fu">group_by</span>(<span class="at">factor_analisis =</span> <span class="fu">as.factor</span>(<span class="sc">!!</span>fr_analisis)) <span class="sc">%&gt;%</span></span>
<span id="cb278-8"><a href="analisis-bivariable.html#cb278-8" aria-hidden="true" tabindex="-1"></a>   <span class="fu">summarise</span>(<span class="at">pct_clientes =</span> <span class="fu">round</span>(<span class="fu">n</span>()<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">nrow</span>(df),<span class="dv">1</span>),</span>
<span id="cb278-9"><a href="analisis-bivariable.html#cb278-9" aria-hidden="true" tabindex="-1"></a>           <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(<span class="sc">!!</span>target)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">1</span>), <span class="at">.groups=</span><span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb278-10"><a href="analisis-bivariable.html#cb278-10" aria-hidden="true" tabindex="-1"></a>   <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>factor_analisis)) <span class="sc">+</span></span>
<span id="cb278-11"><a href="analisis-bivariable.html#cb278-11" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste), <span class="at">group=</span><span class="dv">1</span>, <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb278-12"><a href="analisis-bivariable.html#cb278-12" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_col</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_clientes),<span class="at">fill=</span><span class="st">&quot;yellow&quot;</span>,<span class="at">alpha=</span><span class="fl">0.5</span>)  <span class="sc">+</span></span>
<span id="cb278-13"><a href="analisis-bivariable.html#cb278-13" aria-hidden="true" tabindex="-1"></a>   <span class="fu">geom_text</span>(<span class="at">size=</span><span class="dv">3</span>, <span class="fu">aes</span>(<span class="at">y=</span>pct_interesados <span class="sc">*</span> ajuste, <span class="at">label =</span> <span class="fu">paste</span>(pct_interesados,<span class="st">&#39; %&#39;</span>)), <span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span></span>
<span id="cb278-14"><a href="analisis-bivariable.html#cb278-14" aria-hidden="true" tabindex="-1"></a>   <span class="fu">scale_y_continuous</span>(<span class="at">sec.axis =</span> <span class="fu">sec_axis</span>(<span class="sc">~</span>.<span class="sc">/</span>ajuste, <span class="at">name=</span><span class="st">&quot;% interesados&quot;</span>), <span class="at">name=</span><span class="st">&#39;% clientes&#39;</span>) <span class="sc">+</span></span>
<span id="cb278-15"><a href="analisis-bivariable.html#cb278-15" aria-hidden="true" tabindex="-1"></a>   <span class="fu">theme_light</span>()</span>
<span id="cb278-16"><a href="analisis-bivariable.html#cb278-16" aria-hidden="true" tabindex="-1"></a> </span>
<span id="cb278-17"><a href="analisis-bivariable.html#cb278-17" aria-hidden="true" tabindex="-1"></a>g <span class="sc">+</span> <span class="fu">labs</span>(<span class="at">title =</span> <span class="fu">paste0</span>(<span class="st">&quot;Análisis de la variable &quot;</span>,varib))</span>
<span id="cb278-18"><a href="analisis-bivariable.html#cb278-18" aria-hidden="true" tabindex="-1"></a>}</span>
<span id="cb278-19"><a href="analisis-bivariable.html#cb278-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb278-20"><a href="analisis-bivariable.html#cb278-20" aria-hidden="true" tabindex="-1"></a>bivariable_Age <span class="ot">&lt;-</span> <span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Age&#39;</span>, <span class="fl">0.5</span>)</span>
<span id="cb278-21"><a href="analisis-bivariable.html#cb278-21" aria-hidden="true" tabindex="-1"></a>bivariable_Age</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-164-1.png" width="672" /></p>
<p>Este código automatiza el gráfico anterior y se puede aplicar para más variables, además sirve de ejemplo de uso de <strong>símbolos</strong> en funciones con dplyr ya que en funciones puede ser un problema pasar cadenas de caracteres. Se pueden emplear funciones como <code>group_by_at</code> para evitar esta situación pero en esta función se transforma en símbolo y se referencia mediante !! Como se puede comprobar esta función <code>bivariable</code> se puede replicar con todos los factores en estudio.</p>
<div class="sourceCode" id="cb279"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb279-1"><a href="analisis-bivariable.html#cb279-1" aria-hidden="true" tabindex="-1"></a><span class="fu">grid.arrange</span>(<span class="at">ncol=</span><span class="dv">2</span>,</span>
<span id="cb279-2"><a href="analisis-bivariable.html#cb279-2" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;fr_region2&#39;</span>, <span class="fl">1.5</span>),</span>
<span id="cb279-3"><a href="analisis-bivariable.html#cb279-3" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Gender&#39;</span>, <span class="dv">1</span>),</span>
<span id="cb279-4"><a href="analisis-bivariable.html#cb279-4" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Driving_License&#39;</span>, <span class="dv">1</span>),</span>
<span id="cb279-5"><a href="analisis-bivariable.html#cb279-5" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Vehicle_Damage&#39;</span>, <span class="dv">1</span>),</span>
<span id="cb279-6"><a href="analisis-bivariable.html#cb279-6" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Policy_Sales_Channel&#39;</span>, <span class="dv">1</span>),</span>
<span id="cb279-7"><a href="analisis-bivariable.html#cb279-7" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Previously_Insured&#39;</span>, <span class="dv">1</span>),</span>
<span id="cb279-8"><a href="analisis-bivariable.html#cb279-8" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;Vehicle_Age&#39;</span>, <span class="dv">1</span>))</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-165-1.png" width="1152" /></p>
<p>En este punto se aprecian problemas ya sabidos e identificados en el análisis univariable como son:</p>
<ul>
<li><p>Baja prevalencia del nivel 0 de <code>Driving License</code> ya que no tiene sentido ofrecer seguro de automóviles a aquellos clientes sin carnet.</p></li>
<li><p>El gran número de canales de venta (<code>Policy_Sales_Channel</code>), es un factor con un número inmanejable de niveles.</p></li>
<li><p>El incorrecto orden del factor <code>Vehicle_Age</code>.</p></li>
</ul>
<p>Además surgen otras cuestiones propias del análisis bivariable.</p>
<ul>
<li><p>¿Tiene sentido incluir aquellos clientes con en el factor <code>Vehicle_Damage</code>? ¿Tiene sentido incluir a los clientes que no tienen un seguro de daños cuando casi ninguno muestra interés por el producto?</p></li>
<li><p>¿Tiene sentido incluir a los clientes con un 1 en <code>Previously_Insured</code>? ¿Tiene sentido incluir clientes previamente asegurados en los análisis cuando su interés es tan bajo?</p></li>
</ul>
<p>El científico de datos debe emplear estas aproximaciones para transmitir a los equipos usuarios de los datos las situaciones que describen las variables. No se deben incluir variables sin sentido para mejorar los análisis o la capacidad predictiva de los modelos porque está sacando conclusiones que no tienen utilidad.</p>
<p>Este análisis gráfico se puede emplear en factores pero no se puede usar con variables cuantitativas si éstas no han sido transformadas previamente a factores.</p>
</div>
<div id="correlación-entre-factores.-la-v-de-cramer" class="section level2 hasAnchor" number="11.5">
<h2><span class="header-section-number">11.5</span> Correlación entre factores. La V de Cramer<a href="analisis-bivariable.html#correlación-entre-factores.-la-v-de-cramer" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Es posible medir si dos factores están relacionados entre sí al igual que se hacía con la correlación lineal. Cuando se mide correlación en variables cuantitativas la idea la recoge el gráfico de dispersión y como se coloca cada observación ayuda a comprender el coeficiente de correlación. Sin embargo, en factores un análisis gráfico no recoge tendencia y se opta por medir la diferencia entre los conteos esperados y los conteos obtenidos. Se describe esta labor con un ejemplo sobre los datos de trabajo empleando la librería <code>gmodels</code>.</p>
<div class="sourceCode" id="cb280"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb280-1"><a href="analisis-bivariable.html#cb280-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(gmodels)</span>
<span id="cb280-2"><a href="analisis-bivariable.html#cb280-2" aria-hidden="true" tabindex="-1"></a><span class="fu">CrossTable</span>(train<span class="sc">$</span>Response, train<span class="sc">$</span>Gender, <span class="at">prop.r=</span><span class="cn">TRUE</span>, <span class="at">prop.c=</span><span class="cn">TRUE</span>)</span></code></pre></div>
<pre><code>## 
##  
##    Cell Contents
## |-------------------------|
## |                       N |
## | Chi-square contribution |
## |           N / Row Total |
## |           N / Col Total |
## |         N / Table Total |
## |-------------------------|
## 
##  
## Total Observations in Table:  381109 
## 
##  
##                | train$Gender 
## train$Response |    Female |      Male | Row Total | 
## ---------------|-----------|-----------|-----------|
##              0 |    156835 |    177564 |    334399 | 
##                |    69.461 |    58.989 |           | 
##                |     0.469 |     0.531 |     0.877 | 
##                |     0.896 |     0.862 |           | 
##                |     0.412 |     0.466 |           | 
## ---------------|-----------|-----------|-----------|
##              1 |     18185 |     28525 |     46710 | 
##                |   497.273 |   422.306 |           | 
##                |     0.389 |     0.611 |     0.123 | 
##                |     0.104 |     0.138 |           | 
##                |     0.048 |     0.075 |           | 
## ---------------|-----------|-----------|-----------|
##   Column Total |    175020 |    206089 |    381109 | 
##                |     0.459 |     0.541 |           | 
## ---------------|-----------|-----------|-----------|
## 
## </code></pre>
<p>Esta salida que se obtiene con la función <code>CrossTable</code> de la librería gmodels, se trata de una tabla de contingencia, muy empleada en el ámbito estadístico. Como dice la descripción previa para el cruce de los dos factores se tiene el número de observaciones y la <strong>Chi-square contribution</strong> que es:</p>
<p><span class="math display">\[contribucion- \chi^2 = \frac {(Esperado - Observado)^2}{Esperado}\]</span></p>
<p>Esta es la idea que se emplea para definir si hay dependencia entre factores, ¿qué es el valor esperado? Es el producto de las frecuencias marginales entre el total de observaciones. En el ejemplo se espera para el género <em>Female</em> no está interesado: 334399*175020/381109 = 153569 frente a 156835 que es lo observado, entonces (153569 - 156835)^2/153569 = 69.46 que es un número, no una medida. Además no sabemos la validez estadística que tiene ese valor pero sí es conocido que esta diferencia tiene una distribución asociada llamada Chi-cuadrado que se verá en el siguiente capítulo. Esta prueba da lugar al estadístico de la <span class="math inline">\(\chi^2\)</span> que está influenciado por el tamaño de la muestra y no da ninguna medida, por este motivo se le aplica una corrección por el número total de observaciones y las filas o columnas de la tabla de contingencia y ello permite dar una magnitud, esa corrección da lugar al estadístico V de Cramer. Para la obtención de la V de Cramer se emplea en este caso la librería vcd.</p>
<div class="sourceCode" id="cb282"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb282-1"><a href="analisis-bivariable.html#cb282-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(vcd)</span></code></pre></div>
<pre><code>## Loading required package: grid</code></pre>
<div class="sourceCode" id="cb284"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb284-1"><a href="analisis-bivariable.html#cb284-1" aria-hidden="true" tabindex="-1"></a>tabla<span class="ot">=</span><span class="fu">ftable</span>(train<span class="sc">$</span>Gender,train<span class="sc">$</span>Response)</span>
<span id="cb284-2"><a href="analisis-bivariable.html#cb284-2" aria-hidden="true" tabindex="-1"></a><span class="fu">assocstats</span>(tabla)</span></code></pre></div>
<pre><code>##                     X^2 df P(&gt; X^2)
## Likelihood Ratio 1058.1  1        0
## Pearson          1048.0  1        0
## 
## Phi-Coefficient   : 0.052 
## Contingency Coeff.: 0.052 
## Cramer&#39;s V        : 0.052</code></pre>
<p>En este caso la V de Cramer tiene un valor muy próximo a 0 lo que indica que hay poca relación entre los factores, valores próximos a 1 indican mucha relación. Cuando se trabaje con modelos lineales se verá la importancia que tiene esta medida para las variables input en los procesos de modelización.</p>
<p>En cualquier caso, se ha planteado una descripción gráfica para factores y un análisis de correlación para factores, no es aplicable a variables numéricas. Un factor nunca debe ser tratado como una variable numérica, sin embargo, si es posible agrupar variables numéricas y que se comporten como factores y todos los análisis planteados pueden tener cabida.</p>
</div>
<div id="agrupación-de-variables-cuantitativas" class="section level2 hasAnchor" number="11.6">
<h2><span class="header-section-number">11.6</span> Agrupación de variables cuantitativas<a href="analisis-bivariable.html#agrupación-de-variables-cuantitativas" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para poder emplear un estadístico como el planteado en el apartado anterior las variables cuantitativas pueden estar <strong>trameadas</strong>. Como en ocasiones anteriores se sugiere que esos tramos tengan el sentido de negocio, pero si se desconoce o nunca se ha abordado un análisis de ese tipo se puede empezar por dividir la variable cuantitativa en N tramos de igual tamaño y estudiar como se comporta la variable respuesta en esos N tramos creados. En el ejemplo de trabajo se estudia el comportamiento de la variable <code>Annual_Premium</code> dividida en 10 tramos con el mismo número de observaciones.</p>
<div class="sourceCode" id="cb286"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb286-1"><a href="analisis-bivariable.html#cb286-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Se divide la variable en 10 tramos con el mismo número de observaciones</span></span>
<span id="cb286-2"><a href="analisis-bivariable.html#cb286-2" aria-hidden="true" tabindex="-1"></a>grupos <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb286-3"><a href="analisis-bivariable.html#cb286-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-4"><a href="analisis-bivariable.html#cb286-4" aria-hidden="true" tabindex="-1"></a>train <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Annual_Premium) <span class="sc">%&gt;%</span> </span>
<span id="cb286-5"><a href="analisis-bivariable.html#cb286-5" aria-hidden="true" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">fr_prima =</span> <span class="fu">as.factor</span>(<span class="fu">ceiling</span>((<span class="fu">row_number</span>()<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">*</span> grupos)))</span>
<span id="cb286-6"><a href="analisis-bivariable.html#cb286-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb286-7"><a href="analisis-bivariable.html#cb286-7" aria-hidden="true" tabindex="-1"></a><span class="fu">table</span>(train<span class="sc">$</span>fr_prima)</span></code></pre></div>
<pre><code>## 
##     1     2     3     4     5     6     7     8     9    10 
## 38110 38111 38111 38111 38111 38111 38111 38111 38111 38111</code></pre>
<p>Esa agrupación es la definición de percentil, se ordena la variable a tramificar de menor a mayor y cada registro dividido por el total si es multiplicado por el número de grupos va a dar un número entre 1 y el número de grupos especificado que tendrán el mismo número de registros y cuyo total recoge el total de los registros. Esa variable grupo se trata como un factor reclasificado por lo que es susceptible de aplicar la función de descripción bivariable.</p>
<div class="sourceCode" id="cb288"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb288-1"><a href="analisis-bivariable.html#cb288-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bivariable</span>(train, <span class="st">&#39;Response&#39;</span>, <span class="st">&#39;fr_prima&#39;</span>, <span class="fl">1.5</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-169-1.png" width="672" /></p>
<p>Cada tramo de <code>fr_prima</code> tiene el 10% del total de observaciones, cada corte es un decil de <code>Annual_Premium</code> y, a la vista del gráfico, no parece una buena opción de tramificación pero acerca al científico de datos a conocer mejor como se comporta la variable respuesta frente a una variable cuantitativa.</p>
<p>Existen técnicas para realizar la agrupación de variables como el <strong>W</strong>eight <strong>O</strong>f <strong>E</strong>vidence (WOE) pero la automatización pierden la perspectiva de conocer como se comportan las variables.</p>
<p>Todos los análisis planteados comienzan a ofrecer impresiones sobre la variable target, permiten aproximar a la tarea “identificar que características de nuestros clientes pueden ser eficaces a la hora de crear una campaña comercial”. Pero no dejan de ser apreciaciones visuales y opiniones que <strong>no tienen ningún sustento estadístico</strong>. Es necesario determinar si esas impresiones son estadísticamente significativas y para ello el científico de datos debe tener nociones de muestreo e inferencia estadística.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="probabilidad-distribuciones.html" class="navigation navigation-prev " aria-label="Previous page"><i class="fa fa-angle-left"></i></a>
<a href="muestreo-inferencia.html" class="navigation navigation-next " aria-label="Next page"><i class="fa fa-angle-right"></i></a>
    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rvaquerizo02/edit/master/10-analisis-bivariable.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
