<!DOCTYPE html>
<html lang="" xml:lang="">
<head>

  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <title>Capítulo 17 Modelización estadística. Seleccionar variables y modelo | Introducción a la Estadística para Científicos de Datos con R</title>
  <meta name="description" content="Libro de introducción a la estadística" />
  <meta name="generator" content="bookdown 0.28 and GitBook 2.6.7" />

  <meta property="og:title" content="Capítulo 17 Modelización estadística. Seleccionar variables y modelo | Introducción a la Estadística para Científicos de Datos con R" />
  <meta property="og:type" content="book" />
  
  <meta property="og:description" content="Libro de introducción a la estadística" />
  <meta name="github-repo" content="https://github.com/rvaquerizo02/Estadistica-data-scientist" />

  <meta name="twitter:card" content="summary" />
  <meta name="twitter:title" content="Capítulo 17 Modelización estadística. Seleccionar variables y modelo | Introducción a la Estadística para Científicos de Datos con R" />
  
  <meta name="twitter:description" content="Libro de introducción a la estadística" />
  

<meta name="author" content="Raul Vaquerizo" />


<meta name="date" content="2023-08-21" />

  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <meta name="apple-mobile-web-app-capable" content="yes" />
  <meta name="apple-mobile-web-app-status-bar-style" content="black" />
  
  
<link rel="prev" href="modelizacion-estadistica.html"/>

<script src="libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/fuse.js@6.4.6/dist/fuse.min.js"></script>
<link href="libs/gitbook-2.6.7/css/style.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-table.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-bookdown.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-highlight.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-search.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-fontsettings.css" rel="stylesheet" />
<link href="libs/gitbook-2.6.7/css/plugin-clipboard.css" rel="stylesheet" />








<link href="libs/anchor-sections-1.1.0/anchor-sections.css" rel="stylesheet" />
<link href="libs/anchor-sections-1.1.0/anchor-sections-hash.css" rel="stylesheet" />
<script src="libs/anchor-sections-1.1.0/anchor-sections.js"></script>
<script src="libs/htmlwidgets-1.5.4/htmlwidgets.js"></script>
<link href="libs/datatables-css-0.0.0/datatables-crosstalk.css" rel="stylesheet" />
<script src="libs/datatables-binding-0.24/datatables.js"></script>
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.min.css" rel="stylesheet" />
<link href="libs/dt-core-1.11.3/css/jquery.dataTables.extra.css" rel="stylesheet" />
<script src="libs/dt-core-1.11.3/js/jquery.dataTables.min.js"></script>
<link href="libs/crosstalk-1.2.0/css/crosstalk.min.css" rel="stylesheet" />
<script src="libs/crosstalk-1.2.0/js/crosstalk.min.js"></script>


<style type="text/css">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<link rel="stylesheet" href="style.css" type="text/css" />
</head>

<body>



  <div class="book without-animation with-summary font-size-2 font-family-1" data-basepath=".">

    <div class="book-summary">
      <nav role="navigation">

<ul class="summary">
<li><a href="./">Introducción a la Estadística para Científicos de Datos con R/a></li>

<li class="divider"></li>
<li class="chapter" data-level="1" data-path="index.html"><a href="index.html"><i class="fa fa-check"></i><b>1</b> Introducción</a>
<ul>
<li class="chapter" data-level="1.1" data-path="index.html"><a href="index.html#objetivos"><i class="fa fa-check"></i><b>1.1</b> Objetivos</a></li>
<li class="chapter" data-level="1.2" data-path="index.html"><a href="index.html#entorno-de-trabajo"><i class="fa fa-check"></i><b>1.2</b> Entorno de trabajo</a></li>
</ul></li>
<li class="chapter" data-level="2" data-path="datos.html"><a href="datos.html"><i class="fa fa-check"></i><b>2</b> Datos</a>
<ul>
<li class="chapter" data-level="2.1" data-path="datos.html"><a href="datos.html#qué-son-los-datos"><i class="fa fa-check"></i><b>2.1</b> Qué son los datos</a></li>
<li class="chapter" data-level="2.2" data-path="datos.html"><a href="datos.html#tipos-de-datos"><i class="fa fa-check"></i><b>2.2</b> Tipos de datos</a>
<ul>
<li class="chapter" data-level="2.2.1" data-path="datos.html"><a href="datos.html#datos-internos"><i class="fa fa-check"></i><b>2.2.1</b> Datos internos</a></li>
<li class="chapter" data-level="2.2.2" data-path="datos.html"><a href="datos.html#datos-externos"><i class="fa fa-check"></i><b>2.2.2</b> Datos externos:</a></li>
</ul></li>
<li class="chapter" data-level="2.3" data-path="datos.html"><a href="datos.html#almacenamiento-de-datos"><i class="fa fa-check"></i><b>2.3</b> Almacenamiento de datos</a>
<ul>
<li class="chapter" data-level="2.3.1" data-path="datos.html"><a href="datos.html#sistemas-operacionales"><i class="fa fa-check"></i><b>2.3.1</b> Sistemas operacionales</a></li>
<li class="chapter" data-level="2.3.2" data-path="datos.html"><a href="datos.html#sistemas-informacionales-tradicionales"><i class="fa fa-check"></i><b>2.3.2</b> Sistemas informacionales tradicionales</a></li>
<li class="chapter" data-level="2.3.3" data-path="datos.html"><a href="datos.html#data-lake"><i class="fa fa-check"></i><b>2.3.3</b> Data Lake</a></li>
</ul></li>
<li class="chapter" data-level="2.4" data-path="datos.html"><a href="datos.html#todo-es-álgebra-lineal"><i class="fa fa-check"></i><b>2.4</b> Todo es álgebra lineal</a></li>
<li class="chapter" data-level="2.5" data-path="datos.html"><a href="datos.html#como-se-disponen-los-datos"><i class="fa fa-check"></i><b>2.5</b> Como se disponen los datos</a></li>
<li class="chapter" data-level="2.6" data-path="datos.html"><a href="datos.html#tipos-de-variables"><i class="fa fa-check"></i><b>2.6</b> Tipos de Variables</a>
<ul>
<li class="chapter" data-level="2.6.1" data-path="datos.html"><a href="datos.html#variables-cuantitativas"><i class="fa fa-check"></i><b>2.6.1</b> Variables cuantitativas</a></li>
<li class="chapter" data-level="2.6.2" data-path="datos.html"><a href="datos.html#variables-cualitativas.-factores"><i class="fa fa-check"></i><b>2.6.2</b> Variables cualitativas. Factores</a></li>
</ul></li>
<li class="chapter" data-level="2.7" data-path="datos.html"><a href="datos.html#el-rol-de-las-variables-en-los-datos"><i class="fa fa-check"></i><b>2.7</b> El rol de las variables en los datos</a></li>
</ul></li>
<li class="chapter" data-level="3" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html"><i class="fa fa-check"></i><b>3</b> Manejo de datos con R</a>
<ul>
<li class="chapter" data-level="3.1" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#universo-tidyverse"><i class="fa fa-check"></i><b>3.1</b> Universo tidyverse</a></li>
<li class="chapter" data-level="3.2" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#selección-de-registros"><i class="fa fa-check"></i><b>3.2</b> Selección de registros</a></li>
<li class="chapter" data-level="3.3" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#selección-de-columnas"><i class="fa fa-check"></i><b>3.3</b> Selección de columnas</a></li>
<li class="chapter" data-level="3.4" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#creación-o-actualización-de-variables"><i class="fa fa-check"></i><b>3.4</b> Creación o actualización de variables</a></li>
<li class="chapter" data-level="3.5" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#ordenar-datos"><i class="fa fa-check"></i><b>3.5</b> Ordenar datos</a></li>
<li class="chapter" data-level="3.6" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#sumarizar-valores"><i class="fa fa-check"></i><b>3.6</b> Sumarizar valores</a></li>
<li class="chapter" data-level="3.7" data-path="manejo-de-datos-con-r.html"><a href="manejo-de-datos-con-r.html#combinación-de-acciones"><i class="fa fa-check"></i><b>3.7</b> Combinación de acciones</a></li>
</ul></li>
<li class="chapter" data-level="4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html"><i class="fa fa-check"></i><b>4</b> Uniones de tablas con R</a>
<ul>
<li class="chapter" data-level="4.1" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#uniones-verticales"><i class="fa fa-check"></i><b>4.1</b> Uniones verticales</a></li>
<li class="chapter" data-level="4.2" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#uniones-horizontales-o-join"><i class="fa fa-check"></i><b>4.2</b> Uniones horizontales o <em>join</em></a>
<ul>
<li class="chapter" data-level="4.2.1" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#inner-join"><i class="fa fa-check"></i><b>4.2.1</b> Inner join</a></li>
<li class="chapter" data-level="4.2.2" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#left-join"><i class="fa fa-check"></i><b>4.2.2</b> Left join</a></li>
<li class="chapter" data-level="4.2.3" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#anti-join"><i class="fa fa-check"></i><b>4.2.3</b> Anti join</a></li>
<li class="chapter" data-level="4.2.4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#librería-sqldf"><i class="fa fa-check"></i><b>4.2.4</b> Librería sqldf</a></li>
</ul></li>
<li class="chapter" data-level="4.3" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#duplicidades-en-las-uniones-de-tablas"><i class="fa fa-check"></i><b>4.3</b> Duplicidades en las uniones de tablas</a></li>
<li class="chapter" data-level="4.4" data-path="uniones-de-tablas-con-r.html"><a href="uniones-de-tablas-con-r.html#referencias"><i class="fa fa-check"></i><b>4.4</b> Referencias</a></li>
</ul></li>
<li class="chapter" data-level="5" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html"><i class="fa fa-check"></i><b>5</b> Representación gráfica básica con ggplot</a>
<ul>
<li class="chapter" data-level="5.1" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#histogramas"><i class="fa fa-check"></i><b>5.1</b> Histogramas</a></li>
<li class="chapter" data-level="5.2" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-densidad"><i class="fa fa-check"></i><b>5.2</b> Gráficos de densidad</a></li>
<li class="chapter" data-level="5.3" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-caja-boxplot"><i class="fa fa-check"></i><b>5.3</b> Gráficos de caja (boxplot)</a></li>
<li class="chapter" data-level="5.4" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-tarta"><i class="fa fa-check"></i><b>5.4</b> Gráficos de tarta</a></li>
<li class="chapter" data-level="5.5" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-barras"><i class="fa fa-check"></i><b>5.5</b> Gráficos de barras</a></li>
<li class="chapter" data-level="5.6" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráficos-de-líneas"><i class="fa fa-check"></i><b>5.6</b> Gráficos de líneas</a></li>
<li class="chapter" data-level="5.7" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#gráfico-de-dispersión"><i class="fa fa-check"></i><b>5.7</b> Gráfico de dispersión</a></li>
<li class="chapter" data-level="5.8" data-path="basicos-ggplot.html"><a href="basicos-ggplot.html#múltiples-gráficos-con-gridextra"><i class="fa fa-check"></i><b>5.8</b> Múltiples gráficos con gridExtra</a></li>
</ul></li>
<li class="chapter" data-level="6" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html"><i class="fa fa-check"></i><b>6</b> Descripción numérica de variables</a>
<ul>
<li class="chapter" data-level="6.1" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#transformar-datos-en-información"><i class="fa fa-check"></i><b>6.1</b> Transformar datos en información</a></li>
<li class="chapter" data-level="6.2" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#caso-práctico.-campaña-de-venta-cruzada"><i class="fa fa-check"></i><b>6.2</b> Caso práctico. Campaña de venta cruzada</a></li>
<li class="chapter" data-level="6.3" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#el-rol-de-las-variables-en-el-conjunto-de-datos"><i class="fa fa-check"></i><b>6.3</b> El rol de las variables en el conjunto de datos</a></li>
<li class="chapter" data-level="6.4" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#análisis-descriptivos-de-los-datos"><i class="fa fa-check"></i><b>6.4</b> Análisis descriptivos de los datos</a>
<ul>
<li class="chapter" data-level="6.4.1" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#descritivos-en-variables-cualitativas-factores"><i class="fa fa-check"></i><b>6.4.1</b> Descritivos en variables cualitativas (factores)</a></li>
<li class="chapter" data-level="6.4.2" data-path="descripcion-numerica-variables.html"><a href="descripcion-numerica-variables.html#descritivos-en-variables-cuantitativas"><i class="fa fa-check"></i><b>6.4.2</b> Descritivos en variables cuantitativas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="7" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html"><i class="fa fa-check"></i><b>7</b> Descripción gráfica de datos</a>
<ul>
<li class="chapter" data-level="7.1" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html#descripción-gráfica-de-factores"><i class="fa fa-check"></i><b>7.1</b> Descripción gráfica de factores</a></li>
<li class="chapter" data-level="7.2" data-path="descripcion-grafica-datos.html"><a href="descripcion-grafica-datos.html#descripción-gráfica-de-variables-numéricas"><i class="fa fa-check"></i><b>7.2</b> Descripción gráfica de variables numéricas</a></li>
</ul></li>
<li class="chapter" data-level="8" data-path="problemas-datos.html"><a href="problemas-datos.html"><i class="fa fa-check"></i><b>8</b> Problemas con los datos</a>
<ul>
<li class="chapter" data-level="8.1" data-path="problemas-datos.html"><a href="problemas-datos.html#problemática-con-factores"><i class="fa fa-check"></i><b>8.1</b> Problemática con factores</a>
<ul>
<li class="chapter" data-level="8.1.1" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-niveles-de-pocos-registros"><i class="fa fa-check"></i><b>8.1.1</b> Factores con niveles de pocos registros</a></li>
<li class="chapter" data-level="8.1.2" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-que-aparecen-como-variables-numéricas"><i class="fa fa-check"></i><b>8.1.2</b> Factores que aparecen como variables numéricas</a></li>
<li class="chapter" data-level="8.1.3" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-un-gran-número-de-niveles"><i class="fa fa-check"></i><b>8.1.3</b> Factores con un gran número de niveles</a></li>
<li class="chapter" data-level="8.1.4" data-path="problemas-datos.html"><a href="problemas-datos.html#factores-con-valores-perdidos"><i class="fa fa-check"></i><b>8.1.4</b> Factores con valores perdidos</a></li>
</ul></li>
<li class="chapter" data-level="8.2" data-path="problemas-datos.html"><a href="problemas-datos.html#problemas-con-variables-numéricas"><i class="fa fa-check"></i><b>8.2</b> Problemas con variables numéricas</a>
<ul>
<li class="chapter" data-level="8.2.1" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-modales"><i class="fa fa-check"></i><b>8.2.1</b> Valores modales</a></li>
<li class="chapter" data-level="8.2.2" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-atípicos"><i class="fa fa-check"></i><b>8.2.2</b> Valores atípicos</a></li>
<li class="chapter" data-level="8.2.3" data-path="problemas-datos.html"><a href="problemas-datos.html#variables-numéricas-como-factores"><i class="fa fa-check"></i><b>8.2.3</b> Variables numéricas como factores</a></li>
<li class="chapter" data-level="8.2.4" data-path="problemas-datos.html"><a href="problemas-datos.html#valores-perdidos-en-variables-numéricas"><i class="fa fa-check"></i><b>8.2.4</b> Valores perdidos en variables numéricas</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="9" data-path="analisis-exploratorio-datos-EDA.html"><a href="analisis-exploratorio-datos-EDA.html"><i class="fa fa-check"></i><b>9</b> Análisis Exploratorio de Datos. EDA</a></li>
<li class="chapter" data-level="10" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html"><i class="fa fa-check"></i><b>10</b> Probabilidad y distribuciones</a>
<ul>
<li class="chapter" data-level="10.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#conceptos-básicos-de-probabilidad"><i class="fa fa-check"></i><b>10.1</b> Conceptos básicos de probabilidad</a></li>
<li class="chapter" data-level="10.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-un-evento"><i class="fa fa-check"></i><b>10.2</b> Distribución de un evento</a>
<ul>
<li class="chapter" data-level="10.2.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-conocidas"><i class="fa fa-check"></i><b>10.2.1</b> Distribuciones conocidas</a></li>
<li class="chapter" data-level="10.2.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#obtención-de-probabilidades-con-r"><i class="fa fa-check"></i><b>10.2.2</b> Obtención de probabilidades con R</a></li>
<li class="chapter" data-level="10.2.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#generación-de-números-aleatorios-con-r"><i class="fa fa-check"></i><b>10.2.3</b> Generación de números aleatorios con R</a></li>
</ul></li>
<li class="chapter" data-level="10.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-discretas"><i class="fa fa-check"></i><b>10.3</b> Distribuciones discretas</a>
<ul>
<li class="chapter" data-level="10.3.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-bernoulli"><i class="fa fa-check"></i><b>10.3.1</b> Distribución de Bernoulli</a></li>
<li class="chapter" data-level="10.3.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-binomial"><i class="fa fa-check"></i><b>10.3.2</b> Distribución binomial</a></li>
<li class="chapter" data-level="10.3.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-de-poisson"><i class="fa fa-check"></i><b>10.3.3</b> Distribución de Poisson</a></li>
</ul></li>
<li class="chapter" data-level="10.4" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribuciones-continuas"><i class="fa fa-check"></i><b>10.4</b> Distribuciones continuas</a>
<ul>
<li class="chapter" data-level="10.4.1" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-uniforme"><i class="fa fa-check"></i><b>10.4.1</b> Distribución uniforme</a></li>
<li class="chapter" data-level="10.4.2" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-normal"><i class="fa fa-check"></i><b>10.4.2</b> Distribución normal</a></li>
<li class="chapter" data-level="10.4.3" data-path="probabilidad-distribuciones.html"><a href="probabilidad-distribuciones.html#distribución-gamma"><i class="fa fa-check"></i><b>10.4.3</b> Distribución gamma</a></li>
</ul></li>
</ul></li>
<li class="chapter" data-level="11" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html"><i class="fa fa-check"></i><b>11</b> Análisis bivariable</a>
<ul>
<li class="chapter" data-level="11.1" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#variable-numérica-frente-a-variable-numérica"><i class="fa fa-check"></i><b>11.1</b> Variable numérica frente a variable numérica</a></li>
<li class="chapter" data-level="11.2" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#factores-frente-a-variables-numéricas"><i class="fa fa-check"></i><b>11.2</b> Factores frente a variables numéricas</a></li>
<li class="chapter" data-level="11.3" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#factores-frente-a-factores"><i class="fa fa-check"></i><b>11.3</b> Factores frente a factores</a></li>
<li class="chapter" data-level="11.4" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#propuesta-de-análisis-gráfico-para-el-análisis-bivariable"><i class="fa fa-check"></i><b>11.4</b> Propuesta de análisis gráfico para el análisis bivariable</a></li>
<li class="chapter" data-level="11.5" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#correlación-entre-factores.-la-v-de-cramer"><i class="fa fa-check"></i><b>11.5</b> Correlación entre factores. La V de Cramer</a></li>
<li class="chapter" data-level="11.6" data-path="analisis-bivariable.html"><a href="analisis-bivariable.html#agrupación-de-variables-cuantitativas"><i class="fa fa-check"></i><b>11.6</b> Agrupación de variables cuantitativas</a></li>
</ul></li>
<li class="chapter" data-level="12" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html"><i class="fa fa-check"></i><b>12</b> Muestreo e inferencia estadística</a>
<ul>
<li class="chapter" data-level="12.1" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo"><i class="fa fa-check"></i><b>12.1</b> Muestreo</a>
<ul>
<li class="chapter" data-level="12.1.1" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-aleatorio-simple"><i class="fa fa-check"></i><b>12.1.1</b> Muestreo aleatorio simple</a></li>
<li class="chapter" data-level="12.1.2" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-aleatorio-estratificado"><i class="fa fa-check"></i><b>12.1.2</b> Muestreo aleatorio estratificado</a></li>
<li class="chapter" data-level="12.1.3" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#muestreo-por-conglomerados"><i class="fa fa-check"></i><b>12.1.3</b> Muestreo por conglomerados</a></li>
</ul></li>
<li class="chapter" data-level="12.2" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#inferencia-estadística"><i class="fa fa-check"></i><b>12.2</b> Inferencia estadística</a></li>
<li class="chapter" data-level="12.3" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#estimación-de-parámetros"><i class="fa fa-check"></i><b>12.3</b> Estimación de parámetros</a></li>
<li class="chapter" data-level="12.4" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#intervalos-de-confianza"><i class="fa fa-check"></i><b>12.4</b> Intervalos de confianza</a></li>
<li class="chapter" data-level="12.5" data-path="muestreo-inferencia.html"><a href="muestreo-inferencia.html#contrastes-de-hipótesis"><i class="fa fa-check"></i><b>12.5</b> Contrastes de hipótesis</a></li>
</ul></li>
<li class="chapter" data-level="13" data-path="regresion-lineal.html"><a href="regresion-lineal.html"><i class="fa fa-check"></i><b>13</b> Regresión lineal</a>
<ul>
<li class="chapter" data-level="13.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#modelo-de-regresión-lineal-simple"><i class="fa fa-check"></i><b>13.1</b> Modelo de regresión lineal simple</a></li>
<li class="chapter" data-level="13.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#el-coeficiente-de-determinación-o-r2"><i class="fa fa-check"></i><b>13.2</b> El coeficiente de determinación o <span class="math inline">\(R^2\)</span></a></li>
<li class="chapter" data-level="13.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#transformaciones-de-variables"><i class="fa fa-check"></i><b>13.3</b> Transformaciones de variables</a></li>
<li class="chapter" data-level="13.4" data-path="regresion-lineal.html"><a href="regresion-lineal.html#tramificación-de-variables-en-modelos-lineales"><i class="fa fa-check"></i><b>13.4</b> Tramificación de variables en modelos lineales</a></li>
<li class="chapter" data-level="13.5" data-path="regresion-lineal.html"><a href="regresion-lineal.html#factores-en-modelos-de-regresión"><i class="fa fa-check"></i><b>13.5</b> Factores en modelos de regresión</a></li>
<li class="chapter" data-level="13.6" data-path="regresion-lineal.html"><a href="regresion-lineal.html#modelo-de-regresión-lineal-múltiple"><i class="fa fa-check"></i><b>13.6</b> Modelo de regresión lineal múltiple</a></li>
<li class="chapter" data-level="13.7" data-path="regresion-lineal.html"><a href="regresion-lineal.html#métodos-de-selección-de-variables"><i class="fa fa-check"></i><b>13.7</b> Métodos de selección de variables</a>
<ul>
<li class="chapter" data-level="13.7.1" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-fordward"><i class="fa fa-check"></i><b>13.7.1</b> Método fordward</a></li>
<li class="chapter" data-level="13.7.2" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-backward"><i class="fa fa-check"></i><b>13.7.2</b> Método backward</a></li>
<li class="chapter" data-level="13.7.3" data-path="regresion-lineal.html"><a href="regresion-lineal.html#método-stepwise"><i class="fa fa-check"></i><b>13.7.3</b> Método stepwise</a></li>
</ul></li>
<li class="chapter" data-level="13.8" data-path="regresion-lineal.html"><a href="regresion-lineal.html#el-principio-de-parsimonia"><i class="fa fa-check"></i><b>13.8</b> El principio de parsimonia</a></li>
</ul></li>
<li class="chapter" data-level="14" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html"><i class="fa fa-check"></i><b>14</b> Introducción al diseño de experimentos</a>
<ul>
<li class="chapter" data-level="14.1" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#fundamentos-del-diseño-experimental"><i class="fa fa-check"></i><b>14.1</b> Fundamentos del diseño experimental</a></li>
<li class="chapter" data-level="14.2" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#fuentes-de-variabilidad"><i class="fa fa-check"></i><b>14.2</b> Fuentes de variabilidad</a></li>
<li class="chapter" data-level="14.3" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#planificación"><i class="fa fa-check"></i><b>14.3</b> Planificación</a></li>
<li class="chapter" data-level="14.4" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#bloquear-y-aleatorizar-factores"><i class="fa fa-check"></i><b>14.4</b> Bloquear y aleatorizar factores</a></li>
<li class="chapter" data-level="14.5" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#diseños-factoriales"><i class="fa fa-check"></i><b>14.5</b> Diseños factoriales</a>
<ul>
<li class="chapter" data-level="14.5.1" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#modelo-unifactorial.-ab-testing"><i class="fa fa-check"></i><b>14.5.1</b> Modelo unifactorial. A/B testing</a></li>
</ul></li>
<li class="chapter" data-level="14.6" data-path="introduccion-diseno-experimentos.html"><a href="introduccion-diseno-experimentos.html#modelos-bifactoriales.-interacciones-entre-variables"><i class="fa fa-check"></i><b>14.6</b> Modelos bifactoriales. Interacciones entre variables</a></li>
</ul></li>
<li class="chapter" data-level="15" data-path="modelos-GLM.html"><a href="modelos-GLM.html"><i class="fa fa-check"></i><b>15</b> Modelos GLM. Regresión logística y regresión de poisson</a>
<ul>
<li class="chapter" data-level="15.1" data-path="modelos-GLM.html"><a href="modelos-GLM.html#motivación-de-los-modelos-glm"><i class="fa fa-check"></i><b>15.1</b> Motivación de los modelos GLM</a></li>
<li class="chapter" data-level="15.2" data-path="modelos-GLM.html"><a href="modelos-GLM.html#la-función-de-enlace-en-los-modelos-glm"><i class="fa fa-check"></i><b>15.2</b> La función de enlace en los modelos GLM</a></li>
<li class="chapter" data-level="15.3" data-path="modelos-GLM.html"><a href="modelos-GLM.html#regresión-logística"><i class="fa fa-check"></i><b>15.3</b> Regresión logística</a></li>
<li class="chapter" data-level="15.4" data-path="modelos-GLM.html"><a href="modelos-GLM.html#regresión-de-poisson"><i class="fa fa-check"></i><b>15.4</b> Regresión de poisson</a></li>
<li class="chapter" data-level="15.5" data-path="modelos-GLM.html"><a href="modelos-GLM.html#los-glm-y-el-concepto-microsegmento"><i class="fa fa-check"></i><b>15.5</b> Los GLM y el concepto microsegmento</a></li>
</ul></li>
<li class="chapter" data-level="16" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html"><i class="fa fa-check"></i><b>16</b> Modelización estadística. Conociendo los datos</a>
<ul>
<li class="chapter" data-level="16.1" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#establecer-un-método-para-la-modelización-estadística"><i class="fa fa-check"></i><b>16.1</b> Establecer un método para la modelización estadística</a></li>
<li class="chapter" data-level="16.2" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#un-método-de-modelización-estadística"><i class="fa fa-check"></i><b>16.2</b> Un método de modelización estadística</a></li>
<li class="chapter" data-level="16.3" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#conocimiento-de-los-datos"><i class="fa fa-check"></i><b>16.3</b> Conocimiento de los datos</a>
<ul>
<li class="chapter" data-level="16.3.1" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#muestreo.-datos-de-entrenamiento-datos-de-validación-datos-de-test-y-prueba-ciega."><i class="fa fa-check"></i><b>16.3.1</b> Muestreo. Datos de entrenamiento, datos de validación, datos de test y prueba ciega.</a></li>
<li class="chapter" data-level="16.3.2" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#aproximación-inicial-a-los-datos"><i class="fa fa-check"></i><b>16.3.2</b> Aproximación inicial a los datos</a></li>
<li class="chapter" data-level="16.3.3" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#clasificación-de-factores"><i class="fa fa-check"></i><b>16.3.3</b> Clasificación de factores</a></li>
</ul></li>
<li class="chapter" data-level="16.4" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#el-código-de-reclasificación-de-factores"><i class="fa fa-check"></i><b>16.4</b> El código de reclasificación de factores</a></li>
<li class="chapter" data-level="16.5" data-path="modelizacion-estadistica.html"><a href="modelizacion-estadistica.html#análisis-de-interacciones"><i class="fa fa-check"></i><b>16.5</b> Análisis de interacciones</a></li>
</ul></li>
<li class="chapter" data-level="17" data-path="modelizacion-estadistica-2.html"><a href="modelizacion-estadistica-2.html"><i class="fa fa-check"></i><b>17</b> Modelización estadística. Seleccionar variables y modelo</a>
<ul>
<li class="chapter" data-level="17.1" data-path="modelizacion-estadistica-2.html"><a href="modelizacion-estadistica-2.html#selección-de-variables"><i class="fa fa-check"></i><b>17.1</b> Selección de variables</a></li>
<li class="chapter" data-level="17.2" data-path="modelizacion-estadistica-2.html"><a href="modelizacion-estadistica-2.html#selección-del-modelo"><i class="fa fa-check"></i><b>17.2</b> Selección del modelo</a></li>
<li class="chapter" data-level="17.3" data-path="modelizacion-estadistica-2.html"><a href="modelizacion-estadistica-2.html#la-capacidad-predictiva-del-modelo"><i class="fa fa-check"></i><b>17.3</b> La capacidad predictiva del modelo</a></li>
<li class="chapter" data-level="17.4" data-path="modelizacion-estadistica-2.html"><a href="modelizacion-estadistica-2.html#resultados-finales"><i class="fa fa-check"></i><b>17.4</b> Resultados finales</a></li>
</ul></li>
<li class="divider"></li>
<li><a href="https://github.com/rstudio/bookdown" target="blank">Published with bookdown</a></li>

</ul>

      </nav>
    </div>

    <div class="book-body">
      <div class="body-inner">
        <div class="book-header" role="navigation">
          <h1>
            <i class="fa fa-circle-o-notch fa-spin"></i><a href="./">Introducción a la Estadística para Científicos de Datos con R</a>
          </h1>
        </div>

        <div class="page-wrapper" tabindex="-1" role="main">
          <div class="page-inner">

            <section class="normal" id="section-">
<div id="modelizacion-estadistica-2" class="section level1 hasAnchor" number="17">
<h1><span class="header-section-number">Capítulo 17</span> Modelización estadística. Seleccionar variables y modelo<a href="modelizacion-estadistica-2.html#modelizacion-estadistica-2" class="anchor-section" aria-label="Anchor link to header"></a></h1>
<p>El capítulo anterior comenzó con esta imagen.</p>
<p><img src="imagenes/metodo_modelizacion.png" /></p>
<p>Se trataba de establecer un marco de trabajo, un guión para el científico de datos con los pasos a seguir en el proceso de modelización estadística. Se trabajó la primera parte de ese marco, el conocimiento de los datos, el inicio del proceso de modelización. Este capítulo será el siguiente paso ilustrando como seleccionar variables a partir de los parámetros del modelo y proponer una selección del modelo final midiendo su capacidad predictiva. Es necesario comenzar justo donde finalizó el paso anterior.</p>
<div class="sourceCode" id="cb496"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb496-1"><a href="modelizacion-estadistica-2.html#cb496-1" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb496-2"><a href="modelizacion-estadistica-2.html#cb496-2" tabindex="-1"></a><span class="fu">library</span>(DT)</span>
<span id="cb496-3"><a href="modelizacion-estadistica-2.html#cb496-3" tabindex="-1"></a></span>
<span id="cb496-4"><a href="modelizacion-estadistica-2.html#cb496-4" tabindex="-1"></a>train <span class="ot">&lt;-</span> <span class="fu">read.csv</span>(<span class="st">&quot;./data/train.csv&quot;</span>)</span>
<span id="cb496-5"><a href="modelizacion-estadistica-2.html#cb496-5" tabindex="-1"></a></span>
<span id="cb496-6"><a href="modelizacion-estadistica-2.html#cb496-6" tabindex="-1"></a><span class="co"># Se mantiene el conjunto de datos inicial</span></span>
<span id="cb496-7"><a href="modelizacion-estadistica-2.html#cb496-7" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train <span class="sc">%&gt;%</span> </span>
<span id="cb496-8"><a href="modelizacion-estadistica-2.html#cb496-8" tabindex="-1"></a>  <span class="fu">filter</span>(Previously_Insured <span class="sc">==</span> <span class="dv">0</span> <span class="sc">|</span> Vehicle_Damage <span class="sc">==</span> <span class="st">&quot;Yes&quot;</span>) </span>
<span id="cb496-9"><a href="modelizacion-estadistica-2.html#cb496-9" tabindex="-1"></a></span>
<span id="cb496-10"><a href="modelizacion-estadistica-2.html#cb496-10" tabindex="-1"></a><span class="co"># Clasifiación de factores</span></span>
<span id="cb496-11"><a href="modelizacion-estadistica-2.html#cb496-11" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(</span>
<span id="cb496-12"><a href="modelizacion-estadistica-2.html#cb496-12" tabindex="-1"></a>  <span class="at">fr_antiguedad_vehiculo=</span><span class="fu">case_when</span>(</span>
<span id="cb496-13"><a href="modelizacion-estadistica-2.html#cb496-13" tabindex="-1"></a>  Vehicle_Age<span class="sc">==</span><span class="st">&#39;&lt; 1 Year&#39;</span> <span class="sc">~</span> <span class="st">&#39;1. menos 1 año&#39;</span>,</span>
<span id="cb496-14"><a href="modelizacion-estadistica-2.html#cb496-14" tabindex="-1"></a>  Vehicle_Age<span class="sc">==</span><span class="st">&#39;1-2 Year&#39;</span> <span class="sc">~</span> <span class="st">&#39;2. entre 1-2 años&#39;</span>,</span>
<span id="cb496-15"><a href="modelizacion-estadistica-2.html#cb496-15" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;3. mas 2 años&#39;</span>),</span>
<span id="cb496-16"><a href="modelizacion-estadistica-2.html#cb496-16" tabindex="-1"></a>  <span class="at">fr_sexo =</span> Gender)</span>
<span id="cb496-17"><a href="modelizacion-estadistica-2.html#cb496-17" tabindex="-1"></a></span>
<span id="cb496-18"><a href="modelizacion-estadistica-2.html#cb496-18" tabindex="-1"></a><span class="co"># Agrupación de zonas</span></span>
<span id="cb496-19"><a href="modelizacion-estadistica-2.html#cb496-19" tabindex="-1"></a>fr_zona <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span></span>
<span id="cb496-20"><a href="modelizacion-estadistica-2.html#cb496-20" tabindex="-1"></a>   <span class="fu">group_by</span>(Region_Code) <span class="sc">%&gt;%</span></span>
<span id="cb496-21"><a href="modelizacion-estadistica-2.html#cb496-21" tabindex="-1"></a>   <span class="fu">summarise</span>(<span class="at">clientes =</span> <span class="fu">round</span>(<span class="fu">n</span>()<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">nrow</span>(train2),<span class="dv">1</span>),</span>
<span id="cb496-22"><a href="modelizacion-estadistica-2.html#cb496-22" tabindex="-1"></a>           <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(Response)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">1</span>), </span>
<span id="cb496-23"><a href="modelizacion-estadistica-2.html#cb496-23" tabindex="-1"></a>           <span class="at">.groups=</span><span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb496-24"><a href="modelizacion-estadistica-2.html#cb496-24" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_interesados)) <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">fr_zona =</span> <span class="fu">case_when</span>(</span>
<span id="cb496-25"><a href="modelizacion-estadistica-2.html#cb496-25" tabindex="-1"></a>  pct_interesados<span class="sc">&lt;=</span><span class="dv">12</span> <span class="sc">~</span> <span class="st">&#39;3. bajo interés&#39;</span>,</span>
<span id="cb496-26"><a href="modelizacion-estadistica-2.html#cb496-26" tabindex="-1"></a>  pct_interesados<span class="sc">&lt;=</span><span class="dv">20</span> <span class="sc">~</span> <span class="st">&#39;2. medio interés&#39;</span>,</span>
<span id="cb496-27"><a href="modelizacion-estadistica-2.html#cb496-27" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;1. alto interés&#39;</span>))</span>
<span id="cb496-28"><a href="modelizacion-estadistica-2.html#cb496-28" tabindex="-1"></a></span>
<span id="cb496-29"><a href="modelizacion-estadistica-2.html#cb496-29" tabindex="-1"></a>fr_canal <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span></span>
<span id="cb496-30"><a href="modelizacion-estadistica-2.html#cb496-30" tabindex="-1"></a>   <span class="fu">group_by</span>(Policy_Sales_Channel) <span class="sc">%&gt;%</span></span>
<span id="cb496-31"><a href="modelizacion-estadistica-2.html#cb496-31" tabindex="-1"></a>   <span class="fu">summarise</span>(<span class="at">clientes =</span> <span class="fu">round</span>(<span class="fu">n</span>()<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">nrow</span>(train2),<span class="dv">1</span>),</span>
<span id="cb496-32"><a href="modelizacion-estadistica-2.html#cb496-32" tabindex="-1"></a>           <span class="at">pct_interesados =</span> <span class="fu">round</span>(<span class="fu">sum</span>(Response)<span class="sc">*</span><span class="dv">100</span><span class="sc">/</span><span class="fu">n</span>(),<span class="dv">1</span>), <span class="at">.groups=</span><span class="st">&#39;drop&#39;</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb496-33"><a href="modelizacion-estadistica-2.html#cb496-33" tabindex="-1"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(pct_interesados)) <span class="sc">%&gt;%</span> </span>
<span id="cb496-34"><a href="modelizacion-estadistica-2.html#cb496-34" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fr_canal =</span> <span class="fu">case_when</span>(</span>
<span id="cb496-35"><a href="modelizacion-estadistica-2.html#cb496-35" tabindex="-1"></a>  pct_interesados<span class="sc">&lt;=</span><span class="dv">12</span> <span class="sc">~</span> <span class="st">&#39;3. bajo interés&#39;</span>,</span>
<span id="cb496-36"><a href="modelizacion-estadistica-2.html#cb496-36" tabindex="-1"></a>  pct_interesados<span class="sc">&lt;=</span><span class="dv">20</span> <span class="sc">~</span> <span class="st">&#39;2. medio interés&#39;</span>,</span>
<span id="cb496-37"><a href="modelizacion-estadistica-2.html#cb496-37" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;1. alto interés&#39;</span>))</span>
<span id="cb496-38"><a href="modelizacion-estadistica-2.html#cb496-38" tabindex="-1"></a></span>
<span id="cb496-39"><a href="modelizacion-estadistica-2.html#cb496-39" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span> <span class="fu">left_join</span>(<span class="fu">select</span>(fr_zona, Region_Code, fr_zona)) <span class="sc">%&gt;%</span> </span>
<span id="cb496-40"><a href="modelizacion-estadistica-2.html#cb496-40" tabindex="-1"></a>  <span class="fu">left_join</span>(<span class="fu">select</span>(fr_canal, Policy_Sales_Channel, fr_canal))</span>
<span id="cb496-41"><a href="modelizacion-estadistica-2.html#cb496-41" tabindex="-1"></a></span>
<span id="cb496-42"><a href="modelizacion-estadistica-2.html#cb496-42" tabindex="-1"></a><span class="co"># Agrupación de factores</span></span>
<span id="cb496-43"><a href="modelizacion-estadistica-2.html#cb496-43" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span> </span>
<span id="cb496-44"><a href="modelizacion-estadistica-2.html#cb496-44" tabindex="-1"></a>  <span class="fu">mutate</span>(</span>
<span id="cb496-45"><a href="modelizacion-estadistica-2.html#cb496-45" tabindex="-1"></a>  <span class="at">Age=</span><span class="fu">as.numeric</span>(Age),</span>
<span id="cb496-46"><a href="modelizacion-estadistica-2.html#cb496-46" tabindex="-1"></a>  <span class="at">fr_edad =</span> <span class="fu">case_when</span>(</span>
<span id="cb496-47"><a href="modelizacion-estadistica-2.html#cb496-47" tabindex="-1"></a>  Age <span class="sc">&gt;</span><span class="dv">18</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">22</span> <span class="sc">~</span> <span class="st">&#39;1. Menores 20 años&#39;</span>,</span>
<span id="cb496-48"><a href="modelizacion-estadistica-2.html#cb496-48" tabindex="-1"></a>  Age <span class="sc">&gt;=</span> <span class="dv">23</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">24</span> <span class="sc">~</span> <span class="st">&#39;2. Entre 22 y 23 años&#39;</span>,</span>
<span id="cb496-49"><a href="modelizacion-estadistica-2.html#cb496-49" tabindex="-1"></a>  Age <span class="sc">&gt;=</span> <span class="dv">25</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">30</span> <span class="sc">~</span> <span class="st">&#39;3. Entre 25 y 30 años&#39;</span>,</span>
<span id="cb496-50"><a href="modelizacion-estadistica-2.html#cb496-50" tabindex="-1"></a>  Age <span class="sc">&gt;=</span> <span class="dv">31</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">35</span> <span class="sc">~</span> <span class="st">&#39;4. Entre 31 y 35 años&#39;</span>,</span>
<span id="cb496-51"><a href="modelizacion-estadistica-2.html#cb496-51" tabindex="-1"></a>  Age <span class="sc">&gt;=</span> <span class="dv">36</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">45</span> <span class="sc">~</span> <span class="st">&#39;5. Entre 36 y 45 años&#39;</span>,</span>
<span id="cb496-52"><a href="modelizacion-estadistica-2.html#cb496-52" tabindex="-1"></a>  Age <span class="sc">&gt;=</span> <span class="dv">46</span> <span class="sc">&amp;</span> Age <span class="sc">&lt;=</span><span class="dv">60</span> <span class="sc">~</span> <span class="st">&#39;6. Entre 46 y 60 años&#39;</span>,</span>
<span id="cb496-53"><a href="modelizacion-estadistica-2.html#cb496-53" tabindex="-1"></a>  Age <span class="sc">&gt;</span> <span class="dv">60</span>  <span class="sc">~</span> <span class="st">&#39;7. Mayores 60 años&#39;</span>),</span>
<span id="cb496-54"><a href="modelizacion-estadistica-2.html#cb496-54" tabindex="-1"></a>  </span>
<span id="cb496-55"><a href="modelizacion-estadistica-2.html#cb496-55" tabindex="-1"></a>  <span class="at">fr_prima =</span> <span class="fu">case_when</span>(</span>
<span id="cb496-56"><a href="modelizacion-estadistica-2.html#cb496-56" tabindex="-1"></a>  Annual_Premium <span class="sc">&lt;=</span> <span class="dv">3000</span> <span class="sc">~</span> <span class="st">&#39;1. Menor de 3000 €&#39;</span>,</span>
<span id="cb496-57"><a href="modelizacion-estadistica-2.html#cb496-57" tabindex="-1"></a>  Annual_Premium <span class="sc">&lt;=</span> <span class="dv">40000</span> <span class="sc">~</span> <span class="st">&#39;2. Entre 3000 y 40000 €&#39;</span>,</span>
<span id="cb496-58"><a href="modelizacion-estadistica-2.html#cb496-58" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;3. Más de 40000 €&#39;</span>))</span>
<span id="cb496-59"><a href="modelizacion-estadistica-2.html#cb496-59" tabindex="-1"></a></span>
<span id="cb496-60"><a href="modelizacion-estadistica-2.html#cb496-60" tabindex="-1"></a>grupos <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb496-61"><a href="modelizacion-estadistica-2.html#cb496-61" tabindex="-1"></a>train2 <span class="ot">&lt;-</span> train2 <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(Vintage) <span class="sc">%&gt;%</span> </span>
<span id="cb496-62"><a href="modelizacion-estadistica-2.html#cb496-62" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">fr_antiguedad =</span> <span class="fu">as.factor</span>(<span class="fu">ceiling</span>((<span class="fu">row_number</span>()<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">*</span> grupos)))</span>
<span id="cb496-63"><a href="modelizacion-estadistica-2.html#cb496-63" tabindex="-1"></a></span>
<span id="cb496-64"><a href="modelizacion-estadistica-2.html#cb496-64" tabindex="-1"></a><span class="fu">datatable</span>(<span class="fu">head</span>(train2))</span></code></pre></div>
<div id="htmlwidget-1221621441d31bf06362" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-1221621441d31bf06362">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6"],[329,806,1567,1797,2090,2138],["Male","Male","Female","Female","Male","Female"],[39,38,73,41,42,38],[1,1,1,1,1,1],[28,48,28,28,33,8],[0,0,0,0,0,0],["1-2 Year","1-2 Year","&gt; 2 Years","1-2 Year","1-2 Year","1-2 Year"],["Yes","Yes","Yes","Yes","Yes","Yes"],[38036,2630,29932,2630,29684,41998],[157,124,124,155,124,124],[10,10,10,10,10,10],[0,1,0,1,1,0],["2. entre 1-2 años","2. entre 1-2 años","3. mas 2 años","2. entre 1-2 años","2. entre 1-2 años","2. entre 1-2 años"],["Male","Male","Female","Female","Male","Female"],["1. alto interés","2. medio interés","1. alto interés","1. alto interés","1. alto interés","2. medio interés"],["1. alto interés","1. alto interés","1. alto interés","1. alto interés","1. alto interés","1. alto interés"],["5. Entre 36 y 45 años","5. Entre 36 y 45 años","7. Mayores 60 años","5. Entre 36 y 45 años","5. Entre 36 y 45 años","5. Entre 36 y 45 años"],["2. Entre 3000 y 40000 €","1. Menor de 3000 €","2. Entre 3000 y 40000 €","1. Menor de 3000 €","2. Entre 3000 y 40000 €","3. Más de 40000 €"],["1","1","1","1","1","1"]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>id<\/th>\n      <th>Gender<\/th>\n      <th>Age<\/th>\n      <th>Driving_License<\/th>\n      <th>Region_Code<\/th>\n      <th>Previously_Insured<\/th>\n      <th>Vehicle_Age<\/th>\n      <th>Vehicle_Damage<\/th>\n      <th>Annual_Premium<\/th>\n      <th>Policy_Sales_Channel<\/th>\n      <th>Vintage<\/th>\n      <th>Response<\/th>\n      <th>fr_antiguedad_vehiculo<\/th>\n      <th>fr_sexo<\/th>\n      <th>fr_zona<\/th>\n      <th>fr_canal<\/th>\n      <th>fr_edad<\/th>\n      <th>fr_prima<\/th>\n      <th>fr_antiguedad<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"columnDefs":[{"className":"dt-right","targets":[1,3,4,5,6,9,10,11,12]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Se replica de nuevo el filtrado de datos eliminando a los clientes que no han estado asegurados cuya respuesta siempre es 0 y no tienen interés en comunicaciones comerciales y por el mismo motivo se eliminan a los clientes con garantía de daños creando el objeto <code>train2</code>. Se aplica el código inicial de la reclasificación de factores a la que se llegó de forma univariable. A continuación, se crean los conjuntos de datos de entrenamiento y de test, en este caso no se balanceará la muestra debido a que se dispone de un 21.6% de respuestas positivas y por ese motivo no es necesario disponer de un conjunto de validación.</p>
<div class="sourceCode" id="cb497"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb497-1"><a href="modelizacion-estadistica-2.html#cb497-1" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">12</span>)</span>
<span id="cb497-2"><a href="modelizacion-estadistica-2.html#cb497-2" tabindex="-1"></a>indices <span class="ot">&lt;-</span> <span class="fu">sample</span>(<span class="fu">seq</span>(<span class="dv">1</span><span class="sc">:</span><span class="fu">nrow</span>(train2)) , <span class="fu">round</span>(<span class="fu">nrow</span>(train2) <span class="sc">*</span> <span class="fl">0.70</span>))</span>
<span id="cb497-3"><a href="modelizacion-estadistica-2.html#cb497-3" tabindex="-1"></a></span>
<span id="cb497-4"><a href="modelizacion-estadistica-2.html#cb497-4" tabindex="-1"></a>entrenamiento <span class="ot">&lt;-</span> train2[indices,]</span>
<span id="cb497-5"><a href="modelizacion-estadistica-2.html#cb497-5" tabindex="-1"></a><span class="co"># % de observaciones en entrenamiento</span></span>
<span id="cb497-6"><a href="modelizacion-estadistica-2.html#cb497-6" tabindex="-1"></a><span class="fu">nrow</span>(entrenamiento)<span class="sc">/</span><span class="fu">nrow</span>(train2)</span></code></pre></div>
<pre><code>## [1] 0.6999995</code></pre>
<div class="sourceCode" id="cb499"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb499-1"><a href="modelizacion-estadistica-2.html#cb499-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> train2[<span class="sc">-</span>indices,]</span>
<span id="cb499-2"><a href="modelizacion-estadistica-2.html#cb499-2" tabindex="-1"></a><span class="co"># % de observaciones en test</span></span>
<span id="cb499-3"><a href="modelizacion-estadistica-2.html#cb499-3" tabindex="-1"></a><span class="fu">nrow</span>(test)<span class="sc">/</span><span class="fu">nrow</span>(train2)</span></code></pre></div>
<pre><code>## [1] 0.3000005</code></pre>
<p>El % de observaciones seleccionadas difiere con los planteado en el capítulo anterior debido a que se seleccionan un 70% de observaciones para entrenar el modelo y el 30% para testear, en la fase previa, de cara a agilizar los procesos, se seleccionaba un 50% de las observaciones.</p>
<blockquote>
<p>Para comenzar a conocer los datos y la reclasificación de factores se recomienda trabajar con subconjuntos de datos de menor tamaño debido a la continua interacción con los datos que requiere esa fase.</p>
</blockquote>
<p>Conocidos los factores a emplear y con los conjuntos de datos preparados ya se está en disposición de realizar el primer modelo. Y lo primero es tener claro el objetivo de ese modelo, se pretende <strong>identificar y caracterizar</strong> que clientes de la cartera de salud pueden estar interesados en un seguro de automóviles. El problema de negocio lo describe la variable <code>Response</code> que toma valores 1 - está interesado, 0 - no está interesado; es un problema de <strong>clasificación binomial</strong>. En el capítulo 15 se presentaron los modelos GLM y entre ellos estaba la <strong>regresión logística</strong> que será la técnica elegida para realizar el modelo ya que permite asignar una probabilidad de estar interesado en el seguro de automóviles cliente a cliente en base a unas características y permite describir como son esos clientes a través de los parámetros que ofrece el modelo. Este tipo de modelos se conocen como modelos de propensión a la compra.</p>
<div id="selección-de-variables" class="section level2 hasAnchor" number="17.1">
<h2><span class="header-section-number">17.1</span> Selección de variables<a href="modelizacion-estadistica-2.html#selección-de-variables" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>En realidad ya se ha hecho un filtrado previo de variables basado en la aproximación inicial a los datos y basado en <em>criterios de negocio</em>. Se han creado una serie de factores reclasificados en función de análisis gráficos bivariables donde se estudiaba la variable target frente a un factor. Pero todos esos análisis implican <strong>la acción de una sola variable</strong>, el modelo es una estructura algebraica multivariable que va a tener en cuenta todas las variables y como éstas discriminan la variable target.</p>
<p>En el capítulo 13 dedicado a la regresión lineal se identificó un problema que tienen los modelos de regresión lineal múltiple, <strong>la multicolinealidad</strong>. Los GLM, como modelos con resolución lineal, también adolecen de este problema. Por este motivo el primer criterio para seleccionar variables será el análisis de la correlación de factores que se llevará a cabo mediante la V de Cramer vista en el apartado 5 del capítulo 11 del ensayo.</p>
<p>Para llevar a cabo el análisis de correlaciones vía V de Cramer se van a emplear las librerías <code>vcd</code> y <code>corrplot</code> sólo con los factores reclasificados.</p>
<div class="sourceCode" id="cb501"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb501-1"><a href="modelizacion-estadistica-2.html#cb501-1" tabindex="-1"></a><span class="fu">library</span>(vcd) <span class="co">#Cálculo de estadísticos de correlación </span></span>
<span id="cb501-2"><a href="modelizacion-estadistica-2.html#cb501-2" tabindex="-1"></a><span class="fu">library</span>(corrplot) <span class="co">#Representación gráfica de gráficos de correlación</span></span>
<span id="cb501-3"><a href="modelizacion-estadistica-2.html#cb501-3" tabindex="-1"></a></span>
<span id="cb501-4"><a href="modelizacion-estadistica-2.html#cb501-4" tabindex="-1"></a><span class="co">#Correlaciones entre factores</span></span>
<span id="cb501-5"><a href="modelizacion-estadistica-2.html#cb501-5" tabindex="-1"></a>predictoras <span class="ot">&lt;-</span> <span class="fu">colnames</span>(entrenamiento)</span>
<span id="cb501-6"><a href="modelizacion-estadistica-2.html#cb501-6" tabindex="-1"></a>predictoras <span class="ot">&lt;-</span> predictoras[<span class="fu">substr</span>(predictoras,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;fr_&quot;</span>]</span></code></pre></div>
<p>De nuevo, retiterar la importancia que tiene que las variables participantes en la modelización tengan una característica común para automatizar código, en este caso todas comienzan con el prefijo fr_. A continuación se presenta un bucle <a href="https://stackoverflow.com/questions/44070853/association-matrix-in-r" target=_blank>obtenido en stackoverflow que permite crear la matriz de correlaciones</a>.</p>
<div class="sourceCode" id="cb502"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb502-1"><a href="modelizacion-estadistica-2.html#cb502-1" tabindex="-1"></a>correlaciones <span class="ot">&lt;-</span> entrenamiento <span class="sc">%&gt;%</span></span>
<span id="cb502-2"><a href="modelizacion-estadistica-2.html#cb502-2" tabindex="-1"></a>  <span class="fu">select</span>(predictoras)</span></code></pre></div>
<pre><code>## Note: Using an external vector in selections is ambiguous.
## i Use `all_of(predictoras)` instead of `predictoras` to silence this message.
## i See &lt;https://tidyselect.r-lib.org/reference/faq-external-vector.html&gt;.
## This message is displayed once per session.</code></pre>
<div class="sourceCode" id="cb504"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb504-1"><a href="modelizacion-estadistica-2.html#cb504-1" tabindex="-1"></a><span class="co">#Partimos de una matriz vacía con las dimensiones apropiadas</span></span>
<span id="cb504-2"><a href="modelizacion-estadistica-2.html#cb504-2" tabindex="-1"></a>empty_m <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="at">ncol =</span> <span class="fu">length</span>(correlaciones),</span>
<span id="cb504-3"><a href="modelizacion-estadistica-2.html#cb504-3" tabindex="-1"></a>                  <span class="at">nrow =</span> <span class="fu">length</span>(correlaciones),</span>
<span id="cb504-4"><a href="modelizacion-estadistica-2.html#cb504-4" tabindex="-1"></a>                  <span class="at">dimnames =</span> <span class="fu">list</span>(<span class="fu">names</span>(correlaciones),</span>
<span id="cb504-5"><a href="modelizacion-estadistica-2.html#cb504-5" tabindex="-1"></a>                                  <span class="fu">names</span>(correlaciones)))</span>
<span id="cb504-6"><a href="modelizacion-estadistica-2.html#cb504-6" tabindex="-1"></a></span>
<span id="cb504-7"><a href="modelizacion-estadistica-2.html#cb504-7" tabindex="-1"></a><span class="co">#Calculamos el estadístico y vamos rellenando la matriz</span></span>
<span id="cb504-8"><a href="modelizacion-estadistica-2.html#cb504-8" tabindex="-1"></a>calculate_cramer <span class="ot">&lt;-</span> <span class="cf">function</span>(m, df) {</span>
<span id="cb504-9"><a href="modelizacion-estadistica-2.html#cb504-9" tabindex="-1"></a>  <span class="cf">for</span> (r <span class="cf">in</span> <span class="fu">seq</span>(<span class="fu">nrow</span>(m))){</span>
<span id="cb504-10"><a href="modelizacion-estadistica-2.html#cb504-10" tabindex="-1"></a>    <span class="cf">for</span> (c <span class="cf">in</span> <span class="fu">seq</span>(<span class="fu">ncol</span>(m))){</span>
<span id="cb504-11"><a href="modelizacion-estadistica-2.html#cb504-11" tabindex="-1"></a>      m[[r, c]] <span class="ot">&lt;-</span> <span class="fu">assocstats</span>(<span class="fu">table</span>(df[[r]], df[[c]]))<span class="sc">$</span>cramer</span>
<span id="cb504-12"><a href="modelizacion-estadistica-2.html#cb504-12" tabindex="-1"></a>    }</span>
<span id="cb504-13"><a href="modelizacion-estadistica-2.html#cb504-13" tabindex="-1"></a>  }</span>
<span id="cb504-14"><a href="modelizacion-estadistica-2.html#cb504-14" tabindex="-1"></a>  <span class="fu">return</span>(m)</span>
<span id="cb504-15"><a href="modelizacion-estadistica-2.html#cb504-15" tabindex="-1"></a>}</span>
<span id="cb504-16"><a href="modelizacion-estadistica-2.html#cb504-16" tabindex="-1"></a></span>
<span id="cb504-17"><a href="modelizacion-estadistica-2.html#cb504-17" tabindex="-1"></a>cor_matrix <span class="ot">&lt;-</span> <span class="fu">calculate_cramer</span>(empty_m ,correlaciones)</span>
<span id="cb504-18"><a href="modelizacion-estadistica-2.html#cb504-18" tabindex="-1"></a><span class="fu">remove</span>(correlaciones)</span>
<span id="cb504-19"><a href="modelizacion-estadistica-2.html#cb504-19" tabindex="-1"></a></span>
<span id="cb504-20"><a href="modelizacion-estadistica-2.html#cb504-20" tabindex="-1"></a><span class="co">#Ya se está en disposición de hacer el gráfico</span></span>
<span id="cb504-21"><a href="modelizacion-estadistica-2.html#cb504-21" tabindex="-1"></a><span class="fu">corrplot</span>(cor_matrix, <span class="at">addCoef.col =</span> <span class="st">&#39;black&#39;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-311-1.png" width="672" /></p>
<p>¿Qué valor de la V de Cramer es umbral para determinar que dos factores están correlacionados? A partir de 0.4 ya se tiene sospecha, por encima de 0.6 hay una clara relación. En este caso Edad, canal y antigüedad del vehículo parece que están correlacionados. ¿Se deben eliminar 2 de esas 3 variables? De nuevo hay que apelar a los análisis planteados durante todo el ensayo y a la comunicación con los equipos de negocio para entender porque se está produciendo este hecho. Para entender mejor el problema, se procede a tabular el cruce de esos factores.</p>
<p>Se comienza con el cruce de edad y canal:</p>
<div class="sourceCode" id="cb505"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb505-1"><a href="modelizacion-estadistica-2.html#cb505-1" tabindex="-1"></a><span class="fu">datatable</span>(entrenamiento <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(fr_edad, fr_canal) <span class="sc">%&gt;%</span> </span>
<span id="cb505-2"><a href="modelizacion-estadistica-2.html#cb505-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">conteo=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb505-3"><a href="modelizacion-estadistica-2.html#cb505-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> fr_canal, <span class="at">values_from =</span> conteo), <span class="at">options =</span> <span class="fu">list</span>(<span class="at">dom =</span> <span class="st">&#39;t&#39;</span>))</span></code></pre></div>
<div id="htmlwidget-d2dbf3bead8dcccf443b" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-d2dbf3bead8dcccf443b">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7"],["1. Menores 20 años","2. Entre 22 y 23 años","3. Entre 25 y 30 años","4. Entre 31 y 35 años","5. Entre 36 y 45 años","6. Entre 46 y 60 años","7. Mayores 60 años"],[2124,1893,5428,8797,33083,37942,17762],[40,33,121,236,2069,2717,1983],[12544,10030,9776,2037,1433,1001,433]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>fr_edad<\/th>\n      <th>1. alto interés<\/th>\n      <th>2. medio interés<\/th>\n      <th>3. bajo interés<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","columnDefs":[{"className":"dt-right","targets":[2,3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Se pone de manifiesto la necesidad de agrupar canales con algún sentido de negocio, la agrupación en niveles de interés está provocando la correlación.</p>
<p>¿Qué puede estar pasando con canal y la antigüedad del vehículo?</p>
<div class="sourceCode" id="cb506"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb506-1"><a href="modelizacion-estadistica-2.html#cb506-1" tabindex="-1"></a><span class="fu">datatable</span>(entrenamiento <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(fr_antiguedad_vehiculo, fr_canal) <span class="sc">%&gt;%</span> </span>
<span id="cb506-2"><a href="modelizacion-estadistica-2.html#cb506-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">conteo=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb506-3"><a href="modelizacion-estadistica-2.html#cb506-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> fr_canal, <span class="at">values_from =</span> conteo), <span class="at">options =</span> <span class="fu">list</span>(<span class="at">dom =</span> <span class="st">&#39;t&#39;</span>))</span></code></pre></div>
<div id="htmlwidget-03f340df7e1c0adef4ee" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-03f340df7e1c0adef4ee">{"x":{"filter":"none","vertical":false,"data":[["1","2","3"],["1. menos 1 año","2. entre 1-2 años","3. mas 2 años"],[7213,89276,10540],[201,6331,667],[34198,3009,47]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>fr_antiguedad_vehiculo<\/th>\n      <th>1. alto interés<\/th>\n      <th>2. medio interés<\/th>\n      <th>3. bajo interés<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","columnDefs":[{"className":"dt-right","targets":[2,3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>El bajo interés que tiene el seguro de automóviles entre los clientes con vehículo nuevo está provocando esta situación.</p>
<p>Por ultimo, queda el análisis entre edad y antigüedad del vehículo.</p>
<div class="sourceCode" id="cb507"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb507-1"><a href="modelizacion-estadistica-2.html#cb507-1" tabindex="-1"></a><span class="fu">datatable</span>(entrenamiento <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(fr_edad, fr_antiguedad_vehiculo) <span class="sc">%&gt;%</span> </span>
<span id="cb507-2"><a href="modelizacion-estadistica-2.html#cb507-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">conteo=</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb507-3"><a href="modelizacion-estadistica-2.html#cb507-3" tabindex="-1"></a>  <span class="fu">pivot_wider</span>(<span class="at">names_from =</span> fr_antiguedad_vehiculo, <span class="at">values_from =</span> conteo), <span class="at">options =</span> <span class="fu">list</span>(<span class="at">dom =</span> <span class="st">&#39;t&#39;</span>))</span></code></pre></div>
<div id="htmlwidget-14451259c2660e4be863" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-14451259c2660e4be863">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7"],["1. Menores 20 años","2. Entre 22 y 23 años","3. Entre 25 y 30 años","4. Entre 31 y 35 años","5. Entre 36 y 45 años","6. Entre 46 y 60 años","7. Mayores 60 años"],[13677,11396,12575,3489,203,220,52],[1017,549,2724,7414,34170,36239,16503],[14,11,26,167,2212,5201,3623]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>fr_edad<\/th>\n      <th>1. menos 1 año<\/th>\n      <th>2. entre 1-2 años<\/th>\n      <th>3. mas 2 años<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","columnDefs":[{"className":"dt-right","targets":[2,3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Son los encuestados jóvenes los que concentran los vehículos nuevos, los encuestados con vehículos nuevos son los que se concentran en los canales con menor interés. Parece existir sesgo con la selección de clientes a los que se realiza el cuestionario y por ese motivo se opta por mantener las variables esperando que el propio modelo elimine alguna de ellas. Pero se reitera la importancia que tiene la comunicación con el equipo que ha generado los datos y con los usuarios finales de los modelos ya que se toman decisiones que han de estar consensuadas y el modelo está adoleciendo de problemas.</p>
<p>Se aprecia que el propio proceso de modelización hace que el científico de datos vuelva una y otra vez a la reclasificación de factores y al análisis bivariable. Analizada la correlación de factores se comienza el trabajo con el modelo. Para realizar modelos de regresión logística se emplea la función <code>glm</code> vista en el capítulo 15, el código ya es conocido.</p>
<div class="sourceCode" id="cb508"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb508-1"><a href="modelizacion-estadistica-2.html#cb508-1" tabindex="-1"></a>predictoras <span class="ot">&lt;-</span> <span class="fu">colnames</span>(entrenamiento)</span>
<span id="cb508-2"><a href="modelizacion-estadistica-2.html#cb508-2" tabindex="-1"></a>predictoras <span class="ot">&lt;-</span> predictoras[<span class="fu">substr</span>(predictoras,<span class="dv">1</span>,<span class="dv">3</span>)<span class="sc">==</span><span class="st">&quot;fr_&quot;</span>]</span>
<span id="cb508-3"><a href="modelizacion-estadistica-2.html#cb508-3" tabindex="-1"></a></span>
<span id="cb508-4"><a href="modelizacion-estadistica-2.html#cb508-4" tabindex="-1"></a>formula_modelo <span class="ot">=</span> <span class="fu">as.formula</span>(<span class="fu">paste0</span>(<span class="st">&#39;Response ~&#39;</span>, <span class="fu">paste</span>(predictoras,<span class="at">collapse =</span> <span class="st">&#39;+&#39;</span>)))</span>
<span id="cb508-5"><a href="modelizacion-estadistica-2.html#cb508-5" tabindex="-1"></a>modelo<span class="fl">.1</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> entrenamiento, <span class="at">formula =</span> formula_modelo, <span class="at">family=</span><span class="st">&#39;binomial&#39;</span>)</span></code></pre></div>
<p>Recordar que <code>glm</code> requiere un data frame, una fórmula y especificar la familia de la función de enlace que permite modelizar ese tipo de datos. Para evitar escribir todas las variables presentes en la fórmula se emplea otra de las posibilidades que ofrece emplear un método de identificación de variables. El <code>summary</code> del modelo permite estudiar el test <span class="math inline">\(\beta_i=0\)</span> asociado a cada parámetro del modelo.</p>
<div class="sourceCode" id="cb509"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb509-1"><a href="modelizacion-estadistica-2.html#cb509-1" tabindex="-1"></a><span class="fu">summary</span>(modelo<span class="fl">.1</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = formula_modelo, family = &quot;binomial&quot;, data = entrenamiento)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1614  -0.8031  -0.5740  -0.3240   2.6170  
## 
## Coefficients:
##                                          Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                             -1.669272   0.047369 -35.240  &lt; 2e-16 ***
## fr_antiguedad_vehiculo2. entre 1-2 años -0.085525   0.033123  -2.582 0.009823 ** 
## fr_antiguedad_vehiculo3. mas 2 años      0.269760   0.040033   6.738  1.6e-11 ***
## fr_sexoMale                              0.048691   0.013309   3.658 0.000254 ***
## fr_zona2. medio interés                 -0.307621   0.015458 -19.901  &lt; 2e-16 ***
## fr_zona3. bajo interés                  -0.498077   0.045700 -10.899  &lt; 2e-16 ***
## fr_canal2. medio interés                -0.460158   0.032955 -13.963  &lt; 2e-16 ***
## fr_canal3. bajo interés                 -1.153496   0.030013 -38.433  &lt; 2e-16 ***
## fr_edad2. Entre 22 y 23 años             0.402494   0.044756   8.993  &lt; 2e-16 ***
## fr_edad3. Entre 25 y 30 años             0.764112   0.039693  19.250  &lt; 2e-16 ***
## fr_edad4. Entre 31 y 35 años             1.102822   0.043110  25.582  &lt; 2e-16 ***
## fr_edad5. Entre 36 y 45 años             0.793452   0.043540  18.224  &lt; 2e-16 ***
## fr_edad6. Entre 46 y 60 años             0.589956   0.043609  13.528  &lt; 2e-16 ***
## fr_edad7. Mayores 60 años               -0.149703   0.046925  -3.190 0.001421 ** 
## fr_prima2. Entre 3000 y 40000 \200          0.210079   0.017480  12.018  &lt; 2e-16 ***
## fr_prima3. Más de 40000 \200                0.195554   0.019718   9.917  &lt; 2e-16 ***
## fr_antiguedad2                          -0.025581   0.028705  -0.891 0.372848    
## fr_antiguedad3                          -0.035872   0.028773  -1.247 0.212497    
## fr_antiguedad4                          -0.019917   0.028724  -0.693 0.488067    
## fr_antiguedad5                          -0.010919   0.028707  -0.380 0.703674    
## fr_antiguedad6                          -0.049343   0.028916  -1.706 0.087928 .  
## fr_antiguedad7                           0.003175   0.028660   0.111 0.911797    
## fr_antiguedad8                          -0.011160   0.028749  -0.388 0.697891    
## fr_antiguedad9                          -0.042705   0.028830  -1.481 0.138525    
## fr_antiguedad10                         -0.024550   0.028755  -0.854 0.393235    
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157892  on 151481  degrees of freedom
## Residual deviance: 148106  on 151457  degrees of freedom
## AIC: 148156
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>El trabajo previo en las variables ha permitido que el modelo arroje unos resultados esperados. La única variable que no está aportando al modelo es la antigüedad como cliente, solo un nivel y con un p-valor asociado por encima del 0.05 parece ofrecer un parámetro capaz de discriminar a los clientes interesados. Este hecho ya se intuía en los análisis univariables previos debido a su comportamiento completamente azaroso. Con tantas observaciones y un efecto tan pequeño se puede eliminar esa variable.</p>
<div class="sourceCode" id="cb511"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb511-1"><a href="modelizacion-estadistica-2.html#cb511-1" tabindex="-1"></a>predictoras <span class="ot">&lt;-</span> predictoras[predictoras <span class="sc">!=</span><span class="st">&quot;fr_antiguedad&quot;</span>]</span>
<span id="cb511-2"><a href="modelizacion-estadistica-2.html#cb511-2" tabindex="-1"></a></span>
<span id="cb511-3"><a href="modelizacion-estadistica-2.html#cb511-3" tabindex="-1"></a>formula_modelo <span class="ot">=</span> <span class="fu">as.formula</span>(<span class="fu">paste0</span>(<span class="st">&#39;Response ~&#39;</span>, <span class="fu">paste</span>(predictoras,<span class="at">collapse =</span> <span class="st">&#39;+&#39;</span>)))</span>
<span id="cb511-4"><a href="modelizacion-estadistica-2.html#cb511-4" tabindex="-1"></a>modelo<span class="fl">.2</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> entrenamiento, <span class="at">formula =</span> formula_modelo, <span class="at">family=</span><span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb511-5"><a href="modelizacion-estadistica-2.html#cb511-5" tabindex="-1"></a><span class="fu">summary</span>(modelo<span class="fl">.2</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = formula_modelo, family = &quot;binomial&quot;, data = entrenamiento)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1522  -0.7995  -0.5750  -0.3207   2.6155  
## 
## Coefficients:
##                                         Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                             -1.69080    0.04323 -39.115  &lt; 2e-16 ***
## fr_antiguedad_vehiculo2. entre 1-2 años -0.08536    0.03312  -2.577 0.009961 ** 
## fr_antiguedad_vehiculo3. mas 2 años      0.26983    0.04003   6.741 1.58e-11 ***
## fr_sexoMale                              0.04878    0.01331   3.665 0.000247 ***
## fr_zona2. medio interés                 -0.30778    0.01546 -19.913  &lt; 2e-16 ***
## fr_zona3. bajo interés                  -0.49798    0.04570 -10.897  &lt; 2e-16 ***
## fr_canal2. medio interés                -0.46021    0.03295 -13.965  &lt; 2e-16 ***
## fr_canal3. bajo interés                 -1.15347    0.03001 -38.435  &lt; 2e-16 ***
## fr_edad2. Entre 22 y 23 años             0.40223    0.04475   8.987  &lt; 2e-16 ***
## fr_edad3. Entre 25 y 30 años             0.76392    0.03969  19.246  &lt; 2e-16 ***
## fr_edad4. Entre 31 y 35 años             1.10266    0.04311  25.579  &lt; 2e-16 ***
## fr_edad5. Entre 36 y 45 años             0.79339    0.04354  18.223  &lt; 2e-16 ***
## fr_edad6. Entre 46 y 60 años             0.58963    0.04361  13.521  &lt; 2e-16 ***
## fr_edad7. Mayores 60 años               -0.14987    0.04692  -3.194 0.001404 ** 
## fr_prima2. Entre 3000 y 40000 \200          0.21002    0.01748  12.016  &lt; 2e-16 ***
## fr_prima3. Más de 40000 \200                0.19553    0.01972   9.917  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157892  on 151481  degrees of freedom
## Residual deviance: 148113  on 151466  degrees of freedom
## AIC: 148145
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>En este caso el test <span class="math inline">\(\beta_i=0\)</span> se rechaza en todos los niveles de los factores seleccionados. Esto lo ha facilitado el trabajo previo en los factores. Este <code>modelo.2</code> sería el modelo final, en cualquier caso, se podrían emplear técnicas de selección de variables vistas en capítulos anteriores para contrastar si este trabajo manual tiene el mismo resultado. En el caso de tener cientos de variables este proceso sería más complicado y optar por métodos de selección automáticos puede ahorrar mucho tiempo y esfuerzo.</p>
</div>
<div id="selección-del-modelo" class="section level2 hasAnchor" number="17.2">
<h2><span class="header-section-number">17.2</span> Selección del modelo<a href="modelizacion-estadistica-2.html#selección-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Se selecciona este <code>modelo.2</code> como el modelo final y sus parámetros están describiendo a los clientes con mayor interés. Como se aprecia en la salida anterior los clientes con vehículos antiguos muestran más interés ya que el parámetro asociado es positivo, en un modelo aditivo <em>suma probabilidad</em>, incluso se podría plantear transformar este factor de 3 niveles en un factor de 2 niveles. También aporta probabilidad si el cliente es hombre, pero aporta menos ya que el parámetro es más próximo a 0. En el canal y la zona todos los parámetros restan probabilidad, al nivel que no aparece, el nivel base que es <code>alto interés</code> ya que se recuerda que, si no se modifica previamente, el orden de los niveles se establece por orden lexico-gráfico. Por edad lo que se esperaba, un comportamiento que no es lineal y que en el rango de 31 a 35 años es donde mayor probabilidad, mayor interés demuestran los encuestados por el seguro de automóviles. En cuanto a la prima se produce un hecho curioso, los dos parámetros son significativos, pero su capacidad de discriminar es mínima ya que el valor que tienen se podrían unir en un único nivel.</p>
<p>Cuanto más trabajados estén los niveles de los factores en la fase de conocimiento menos problemas tendrá el científico de datos en esta fase, aun así se va a optar por agrupar la prima en dos niveles (&lt;=3000 y &gt;3000 €) para dar mayor sencillez al modelo.</p>
<div class="sourceCode" id="cb513"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb513-1"><a href="modelizacion-estadistica-2.html#cb513-1" tabindex="-1"></a>entrenamiento <span class="ot">&lt;-</span> entrenamiento <span class="sc">%&gt;%</span> </span>
<span id="cb513-2"><a href="modelizacion-estadistica-2.html#cb513-2" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">fr_prima =</span> <span class="fu">case_when</span>(</span>
<span id="cb513-3"><a href="modelizacion-estadistica-2.html#cb513-3" tabindex="-1"></a>  Annual_Premium <span class="sc">&lt;=</span> <span class="dv">3000</span> <span class="sc">~</span> <span class="st">&#39;1. Menor de 3000 €&#39;</span>,</span>
<span id="cb513-4"><a href="modelizacion-estadistica-2.html#cb513-4" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;2. Mayor de 3000 €&#39;</span>))</span>
<span id="cb513-5"><a href="modelizacion-estadistica-2.html#cb513-5" tabindex="-1"></a></span>
<span id="cb513-6"><a href="modelizacion-estadistica-2.html#cb513-6" tabindex="-1"></a>modelo<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">glm</span>(<span class="at">data =</span> entrenamiento, <span class="at">formula =</span> formula_modelo, <span class="at">family=</span><span class="st">&#39;binomial&#39;</span>)</span>
<span id="cb513-7"><a href="modelizacion-estadistica-2.html#cb513-7" tabindex="-1"></a><span class="fu">summary</span>(modelo<span class="fl">.3</span>)</span></code></pre></div>
<pre><code>## 
## Call:
## glm(formula = formula_modelo, family = &quot;binomial&quot;, data = entrenamiento)
## 
## Deviance Residuals: 
##     Min       1Q   Median       3Q      Max  
## -1.1498  -0.7976  -0.5734  -0.3202   2.6152  
## 
## Coefficients:
##                                         Estimate Std. Error z value Pr(&gt;|z|)    
## (Intercept)                             -1.69153    0.04322 -39.138  &lt; 2e-16 ***
## fr_antiguedad_vehiculo2. entre 1-2 años -0.08458    0.03311  -2.554 0.010636 *  
## fr_antiguedad_vehiculo3. mas 2 años      0.26897    0.04002   6.721 1.81e-11 ***
## fr_sexoMale                              0.04896    0.01331   3.679 0.000234 ***
## fr_zona2. medio interés                 -0.30688    0.01543 -19.892  &lt; 2e-16 ***
## fr_zona3. bajo interés                  -0.49539    0.04562 -10.860  &lt; 2e-16 ***
## fr_canal2. medio interés                -0.46039    0.03295 -13.971  &lt; 2e-16 ***
## fr_canal3. bajo interés                 -1.15200    0.02997 -38.438  &lt; 2e-16 ***
## fr_edad2. Entre 22 y 23 años             0.40225    0.04475   8.988  &lt; 2e-16 ***
## fr_edad3. Entre 25 y 30 años             0.76413    0.03969  19.252  &lt; 2e-16 ***
## fr_edad4. Entre 31 y 35 años             1.10291    0.04311  25.585  &lt; 2e-16 ***
## fr_edad5. Entre 36 y 45 años             0.79322    0.04354  18.220  &lt; 2e-16 ***
## fr_edad6. Entre 46 y 60 años             0.58850    0.04359  13.501  &lt; 2e-16 ***
## fr_edad7. Mayores 60 años               -0.15149    0.04689  -3.231 0.001235 ** 
## fr_prima2. Mayor de 3000 \200               0.20533    0.01676  12.252  &lt; 2e-16 ***
## ---
## Signif. codes:  0 &#39;***&#39; 0.001 &#39;**&#39; 0.01 &#39;*&#39; 0.05 &#39;.&#39; 0.1 &#39; &#39; 1
## 
## (Dispersion parameter for binomial family taken to be 1)
## 
##     Null deviance: 157892  on 151481  degrees of freedom
## Residual deviance: 148113  on 151467  degrees of freedom
## AIC: 148143
## 
## Number of Fisher Scoring iterations: 5</code></pre>
<p>Qué sucede si durante el proceso de modelización se vuelve a reclasificar un factor. Que será necesario incluirlo en el código de creación de los niveles de los factores.</p>
<p>Y por supuesto sería necesario volver a ejecutar entrenamiento y test. Sin embargo, en este caso se opta por ejecutar la reclasificación sobre el conjunto de datos de entrenamiento. Pero estas situaciones se deben manejar con cuidado porque el código y el proceso de generación de los datos para la tabla de modelización final <strong>son parte de la documentación</strong> que el científico de datos tiene que entregar cuando realice un modelo.</p>
<div class="sourceCode" id="cb515"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb515-1"><a href="modelizacion-estadistica-2.html#cb515-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">fr_prima =</span> <span class="fu">case_when</span>(</span>
<span id="cb515-2"><a href="modelizacion-estadistica-2.html#cb515-2" tabindex="-1"></a>  Annual_Premium <span class="sc">&lt;=</span> <span class="dv">3000</span> <span class="sc">~</span> <span class="st">&#39;1. Menor de 3000 €&#39;</span>,</span>
<span id="cb515-3"><a href="modelizacion-estadistica-2.html#cb515-3" tabindex="-1"></a>  <span class="cn">TRUE</span> <span class="sc">~</span> <span class="st">&#39;2. Mayor de 3000 €&#39;</span>))</span></code></pre></div>
<p>El llamado <code>modelo.3</code> será un candidato a ser el modelo final, para seleccionar el modelo que habría de ser puesto en producción además del comportamiento de los parámetros y del código necesario para <em>productivizarlo</em> es evidente que es necesario estudiar su capacidad predictiva.</p>
</div>
<div id="la-capacidad-predictiva-del-modelo" class="section level2 hasAnchor" number="17.3">
<h2><span class="header-section-number">17.3</span> La capacidad predictiva del modelo<a href="modelizacion-estadistica-2.html#la-capacidad-predictiva-del-modelo" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>Para medir la capacidad predictiva del modelo se determinan en cuantas ocasiones acierta y cuantas ocasiones falla el modelo. Para esta labor se reservó un conjunto de datos que permite testear este comportamiento. En esta ocasión, en vez de medir la capacidad predictiva de una forma más ortodoxa a través de matrices de confusión y curvas ROC se va a estudiar cuanto mejora el modelo a un comportamiento azaroso. El objetivo del problema que está sirviendo de hilo conductor del ensayo es identificar que características y que <strong>clientes son más propensos a contratar un producto</strong> y por ello se va a estudiar cuanto mejora una posible selección de clientes a una selección al azar.</p>
<p>Para entender mejor que se pretende, seleccionando al azar el 10% de los clientes cuántos clientes interesados se espera encontrar.</p>
<div class="sourceCode" id="cb516"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb516-1"><a href="modelizacion-estadistica-2.html#cb516-1" tabindex="-1"></a>azar <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">sample_frac</span>(<span class="fl">0.1</span>)</span>
<span id="cb516-2"><a href="modelizacion-estadistica-2.html#cb516-2" tabindex="-1"></a></span>
<span id="cb516-3"><a href="modelizacion-estadistica-2.html#cb516-3" tabindex="-1"></a><span class="co"># Testeo % respuestas positivas tiene el conjunto de datos de partida</span></span>
<span id="cb516-4"><a href="modelizacion-estadistica-2.html#cb516-4" tabindex="-1"></a><span class="fu">sum</span>(azar<span class="sc">$</span>Response)<span class="sc">/</span><span class="fu">nrow</span>(azar)</span></code></pre></div>
<pre><code>## [1] 0.2173444</code></pre>
<div class="sourceCode" id="cb518"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb518-1"><a href="modelizacion-estadistica-2.html#cb518-1" tabindex="-1"></a><span class="co"># Testeo % respuestas positivas tiene una muestra al azar </span></span>
<span id="cb518-2"><a href="modelizacion-estadistica-2.html#cb518-2" tabindex="-1"></a><span class="fu">sum</span>(test<span class="sc">$</span>Response)<span class="sc">/</span><span class="fu">nrow</span>(test)</span></code></pre></div>
<pre><code>## [1] 0.2155389</code></pre>
<p>El % es análogo porque es una selección al azar del 10% de las observaciones, ya que a todos los clientes les da la misma probabilidad independientemente de si están interesados en el seguro de automóviles o no. Pero el científico de datos ha creado una estructura matemática que permite establecer una probabilidad de ese interés en el seguro de autos en base a unas características de los clientes. De esta manera el primer paso es añadir esa probabilidad a los datos de test del modelo candidato a ser el final.</p>
<div class="sourceCode" id="cb520"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb520-1"><a href="modelizacion-estadistica-2.html#cb520-1" tabindex="-1"></a>probabilidad_modelo<span class="fl">.3</span> <span class="ot">&lt;-</span> <span class="fu">predict</span>(<span class="at">object=</span>modelo<span class="fl">.3</span>, <span class="at">newdata=</span>test, <span class="at">type =</span> <span class="st">&#39;response&#39;</span>)</span>
<span id="cb520-2"><a href="modelizacion-estadistica-2.html#cb520-2" tabindex="-1"></a>test<span class="sc">$</span>probabilidad_modelo<span class="fl">.3</span> <span class="ot">=</span> probabilidad_modelo<span class="fl">.3</span></span></code></pre></div>
<p>Este proceso de emplear la estructura matemática de un modelo a un conjunto de datos es lo que se denomina <strong>escorear un modelo</strong> y permite obtener un <em>output</em> registro a registro con el resultado del modelo, en este caso la probabilidad de mostrar interés en el seguro de automóviles. Ahora, ordenando el conjunto de datos por esa probabilidad de mayor a menor, si el modelo tiene un correcto funcionamiento, al seleccionar el 10% de las primeras observaciones el % de interesados hace superar a ese 21% de partida.</p>
<div class="sourceCode" id="cb521"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb521-1"><a href="modelizacion-estadistica-2.html#cb521-1" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(probabilidad_modelo<span class="fl">.3</span>)) </span>
<span id="cb521-2"><a href="modelizacion-estadistica-2.html#cb521-2" tabindex="-1"></a></span>
<span id="cb521-3"><a href="modelizacion-estadistica-2.html#cb521-3" tabindex="-1"></a>porcen_mas_interesados<span class="ot">=</span>test <span class="sc">%&gt;%</span> <span class="fu">filter</span>(<span class="fu">row_number</span>()<span class="sc">&lt;=</span><span class="fu">round</span>(<span class="fu">nrow</span>(test)<span class="sc">*</span><span class="fl">0.1</span>,<span class="dv">0</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb521-4"><a href="modelizacion-estadistica-2.html#cb521-4" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">porcen_interesados=</span><span class="fu">sum</span>(Response)<span class="sc">/</span><span class="fu">round</span>(<span class="fu">nrow</span>(test)<span class="sc">*</span><span class="fl">0.1</span>,<span class="dv">0</span>))</span>
<span id="cb521-5"><a href="modelizacion-estadistica-2.html#cb521-5" tabindex="-1"></a>porcen_mas_interesados <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">round</span>(porcen_mas_interesados,<span class="dv">4</span>))</span>
<span id="cb521-6"><a href="modelizacion-estadistica-2.html#cb521-6" tabindex="-1"></a></span>
<span id="cb521-7"><a href="modelizacion-estadistica-2.html#cb521-7" tabindex="-1"></a>porcen_interesados<span class="ot">=</span>test <span class="sc">%&gt;%</span> </span>
<span id="cb521-8"><a href="modelizacion-estadistica-2.html#cb521-8" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">porcen_interesados=</span><span class="fu">sum</span>(Response)<span class="sc">/</span><span class="fu">round</span>(<span class="fu">nrow</span>(test),<span class="dv">0</span>))</span>
<span id="cb521-9"><a href="modelizacion-estadistica-2.html#cb521-9" tabindex="-1"></a>porcen_interesados <span class="ot">=</span> <span class="fu">as.numeric</span>(<span class="fu">round</span>(porcen_interesados,<span class="dv">4</span>))</span>
<span id="cb521-10"><a href="modelizacion-estadistica-2.html#cb521-10" tabindex="-1"></a></span>
<span id="cb521-11"><a href="modelizacion-estadistica-2.html#cb521-11" tabindex="-1"></a>porcen_mas_interesados;porcen_interesados</span></code></pre></div>
<pre><code>## [1] 0.3666</code></pre>
<pre><code>## [1] 0.2155</code></pre>
<p>Se observa que el modelo estaría seleccionando un 36.66% de interesados frente al 21.55% global por lo que el 10% de las observaciones están mejorando aproximadamente un 1.7011601 veces a una selección al azar, a ese dato se le va a denominar <strong>ganancia</strong> y se va a considerar un buen modelo si el 10% de las observaciones que el modelo identifica con mayor probabilidad supera en 2.5 veces al azar. En la situación que se está trabajando no es el caso, 1.7011601 está lejos del 2.5 exigido. Pero en este caso superar en 2.5 veces al azar implicaría seleccionar un 66% de interesados en el 10% de observaciones, es decir, el modelo sería excelente, demasiado bueno, y si esto se produce el científico de datos debe desconfiar en ese resultado ya que puede existir alguna variable esté distorsionando resultados.</p>
<p>Ordenadas las observaciones por la probabilidad que asigna el modelo se puede obtener el % de interesados y representar gráficamente una curva de ganancia con respecto al azar.</p>
<div class="sourceCode" id="cb524"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb524-1"><a href="modelizacion-estadistica-2.html#cb524-1" tabindex="-1"></a>grupos <span class="ot">=</span> <span class="dv">10</span></span>
<span id="cb524-2"><a href="modelizacion-estadistica-2.html#cb524-2" tabindex="-1"></a>test <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">arrange</span>(<span class="fu">desc</span>(probabilidad_modelo<span class="fl">.3</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb524-3"><a href="modelizacion-estadistica-2.html#cb524-3" tabindex="-1"></a><span class="fu">mutate</span>(<span class="at">percentil_modelo =</span> <span class="fu">as.factor</span>(<span class="fu">ceiling</span>((<span class="fu">row_number</span>()<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">*</span> grupos)))</span>
<span id="cb524-4"><a href="modelizacion-estadistica-2.html#cb524-4" tabindex="-1"></a></span>
<span id="cb524-5"><a href="modelizacion-estadistica-2.html#cb524-5" tabindex="-1"></a>ganancia <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(percentil_modelo) <span class="sc">%&gt;%</span> </span>
<span id="cb524-6"><a href="modelizacion-estadistica-2.html#cb524-6" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">percentil_interesados =</span> <span class="fu">sum</span>(Response)<span class="sc">/</span><span class="fu">n</span>()) <span class="sc">%&gt;%</span> </span>
<span id="cb524-7"><a href="modelizacion-estadistica-2.html#cb524-7" tabindex="-1"></a>  <span class="fu">as_tibble</span>() <span class="sc">%&gt;%</span> </span>
<span id="cb524-8"><a href="modelizacion-estadistica-2.html#cb524-8" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">ganancia =</span> percentil_interesados<span class="sc">/</span>porcen_interesados)</span>
<span id="cb524-9"><a href="modelizacion-estadistica-2.html#cb524-9" tabindex="-1"></a></span>
<span id="cb524-10"><a href="modelizacion-estadistica-2.html#cb524-10" tabindex="-1"></a>ganancia <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>percentil_modelo,<span class="at">y=</span>ganancia, <span class="at">group=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<span id="cb524-11"><a href="modelizacion-estadistica-2.html#cb524-11" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="at">color=</span><span class="st">&quot;red&quot;</span>) <span class="sc">+</span> <span class="fu">geom_hline</span>(<span class="at">yintercept =</span> <span class="dv">1</span>, <span class="at">color=</span><span class="st">&#39;blue&#39;</span>) </span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-324-1.png" width="672" /></p>
<p>Se aprecia como los percentiles con mayor probabilidad están ganando al azar, pero en el mejor percentil se llega a mejorar en 2 veces a una selección de clientes sin emplear el modelo. Otra forma de ver esta ganancia se consigue acumulando el número de respuestas positivas en función del percentil de probabilidad del modelo.</p>
<div class="sourceCode" id="cb525"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb525-1"><a href="modelizacion-estadistica-2.html#cb525-1" tabindex="-1"></a>ganancia <span class="ot">&lt;-</span> test <span class="sc">%&gt;%</span> <span class="fu">group_by</span>(percentil_modelo) <span class="sc">%&gt;%</span> </span>
<span id="cb525-2"><a href="modelizacion-estadistica-2.html#cb525-2" tabindex="-1"></a>  <span class="fu">summarise</span>(<span class="at">numero_interesados =</span> <span class="fu">sum</span>(Response)) <span class="sc">%&gt;%</span> </span>
<span id="cb525-3"><a href="modelizacion-estadistica-2.html#cb525-3" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">acumulado_interesados =</span> <span class="fu">cumsum</span>(numero_interesados),</span>
<span id="cb525-4"><a href="modelizacion-estadistica-2.html#cb525-4" tabindex="-1"></a>         <span class="at">pct_acumulado_interesados =</span> <span class="fu">round</span>(acumulado_interesados<span class="sc">/</span><span class="fu">sum</span>(test<span class="sc">$</span>Response),<span class="dv">3</span>)) <span class="sc">%&gt;%</span> </span>
<span id="cb525-5"><a href="modelizacion-estadistica-2.html#cb525-5" tabindex="-1"></a>  <span class="fu">as_tibble</span>() </span>
<span id="cb525-6"><a href="modelizacion-estadistica-2.html#cb525-6" tabindex="-1"></a></span>
<span id="cb525-7"><a href="modelizacion-estadistica-2.html#cb525-7" tabindex="-1"></a>ganancia<span class="sc">$</span>pct_esperado_interesados <span class="ot">=</span> <span class="fu">seq</span>(<span class="fl">0.1</span>,<span class="dv">1</span>,<span class="at">by=</span><span class="fl">0.1</span>)</span>
<span id="cb525-8"><a href="modelizacion-estadistica-2.html#cb525-8" tabindex="-1"></a></span>
<span id="cb525-9"><a href="modelizacion-estadistica-2.html#cb525-9" tabindex="-1"></a><span class="fu">datatable</span>(<span class="fu">select</span>(ganancia, <span class="sc">-</span>acumulado_interesados), <span class="at">options =</span> <span class="fu">list</span>(<span class="at">dom =</span> <span class="st">&#39;t&#39;</span>))</span></code></pre></div>
<div id="htmlwidget-0073a80c298269af37dc" style="width:100%;height:auto;" class="datatables html-widget"></div>
<script type="application/json" data-for="htmlwidget-0073a80c298269af37dc">{"x":{"filter":"none","vertical":false,"data":[["1","2","3","4","5","6","7","8","9","10"],["1","2","3","4","5","6","7","8","9","10"],[2380,2072,1827,1808,1707,1367,1079,836,558,359],[0.17,0.318,0.449,0.578,0.7,0.798,0.875,0.934,0.974,1],[0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9,1]],"container":"<table class=\"display\">\n  <thead>\n    <tr>\n      <th> <\/th>\n      <th>percentil_modelo<\/th>\n      <th>numero_interesados<\/th>\n      <th>pct_acumulado_interesados<\/th>\n      <th>pct_esperado_interesados<\/th>\n    <\/tr>\n  <\/thead>\n<\/table>","options":{"dom":"t","columnDefs":[{"className":"dt-right","targets":[2,3,4]},{"orderable":false,"targets":0}],"order":[],"autoWidth":false,"orderClasses":false}},"evals":[],"jsHooks":[]}</script>
<p>Antes de realizar el gráfico se describe la tabla generada. Se contabilizan las respuestas positivas, éstas suponen un % sobre el total que se va acumulando hasta llegar al 100%. Por otro lado, en una selección al azar, donde todas las observaciones tienen la misma probabilidad de ser seleccionadas se esperaría seleccionar el 10% de las observaciones en el primer percentil, el 20% de las observaciones en el segundo percentil y así hasta llegar al 100%, este campo se denomina <code>pct_esperado_interesados</code> y se crea artificialmente. Estos datos se representan gráficamente:</p>
<div class="sourceCode" id="cb526"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb526-1"><a href="modelizacion-estadistica-2.html#cb526-1" tabindex="-1"></a>ganancia <span class="sc">%&gt;%</span> <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>percentil_modelo,<span class="at">group=</span><span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb526-2"><a href="modelizacion-estadistica-2.html#cb526-2" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_acumulado_interesados), <span class="at">color=</span><span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb526-3"><a href="modelizacion-estadistica-2.html#cb526-3" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_esperado_interesados), <span class="at">color=</span><span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-326-1.png" width="672" /></p>
<p>En ese gráfico se echa en falta el punto (0,0) que se puede añadir.</p>
<div class="sourceCode" id="cb527"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb527-1"><a href="modelizacion-estadistica-2.html#cb527-1" tabindex="-1"></a>ganancia<span class="sc">$</span>percentil_modelo <span class="ot">=</span> <span class="fu">as.numeric</span>(ganancia<span class="sc">$</span>percentil_modelo)<span class="sc">*</span><span class="dv">10</span></span>
<span id="cb527-2"><a href="modelizacion-estadistica-2.html#cb527-2" tabindex="-1"></a></span>
<span id="cb527-3"><a href="modelizacion-estadistica-2.html#cb527-3" tabindex="-1"></a><span class="fu">rbind.data.frame</span>(ganancia,</span>
<span id="cb527-4"><a href="modelizacion-estadistica-2.html#cb527-4" tabindex="-1"></a>                 <span class="fu">data.frame</span>(<span class="at">percentil_modelo=</span><span class="dv">0</span>,<span class="at">numero_interesados=</span><span class="dv">0</span>,<span class="at">acumulado_interesados=</span><span class="dv">0</span>,</span>
<span id="cb527-5"><a href="modelizacion-estadistica-2.html#cb527-5" tabindex="-1"></a>                            <span class="at">pct_acumulado_interesados=</span><span class="dv">0</span>, <span class="at">pct_esperado_interesados=</span><span class="dv">0</span>) ) <span class="sc">%&gt;%</span> </span>
<span id="cb527-6"><a href="modelizacion-estadistica-2.html#cb527-6" tabindex="-1"></a>  <span class="fu">ggplot</span>(<span class="fu">aes</span>(<span class="at">x=</span>percentil_modelo,<span class="at">group=</span><span class="dv">1</span>)) <span class="sc">+</span> </span>
<span id="cb527-7"><a href="modelizacion-estadistica-2.html#cb527-7" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_acumulado_interesados), <span class="at">color=</span><span class="st">&#39;blue&#39;</span>) <span class="sc">+</span></span>
<span id="cb527-8"><a href="modelizacion-estadistica-2.html#cb527-8" tabindex="-1"></a>  <span class="fu">geom_line</span>(<span class="fu">aes</span>(<span class="at">y=</span>pct_esperado_interesados), <span class="at">color=</span><span class="st">&#39;red&#39;</span>)</span></code></pre></div>
<p><img src="estadistica-data-scientist_files/figure-html/unnamed-chunk-327-1.png" width="672" /></p>
<p>Este gráfico puede ser familiar para el científico de datos porque se asemeja a la curva ROC pero no tiene nada que ver puesto que la curva ROC lo que mide es la relación entre los aciertos del modelo y los errores a la hora de asignar a las observaciones un resultado positivo siendo éste negativo. En este ensayo no se entra a valorar este método de medición de la precisión del modelo y se ilustra la ganancia. Hay literatura y buenos ejemplos de este método como por ejemplo:</p>
<ul>
<li><p><a href="https://daviddalpiaz.github.io/r4sl/logistic-regression.html#roc-curves" target="_blank"> R for statistical learning</a></p></li>
<li><p><a href="http://www.hrc.es/bioest/roc_1.html" target="_blank"> Material de bioestadística del Hospital Ramón y Cajal</a></p></li>
<li><p><a href="https://bookdown.org/brianmachut/uofm_analytics_r_hw_sol_2/logreg.html" target="_blank"> Datanalytics with R</a></p></li>
</ul>
<p>Los modelos que realice el científico de datos han de contar una historia acerca de los datos y los equipos de negocio que empleen los datos es posible que no comprendan que es una curva ROC, sin embargo, en modelos de propensión a la compra es más sencillo transmitir la idea de cuanto se mejora con respecto a una selección al azar para elaborar casos de negocio en base a hipótesis planteadas durante el proceso de modelización.</p>
</div>
<div id="resultados-finales" class="section level2 hasAnchor" number="17.4">
<h2><span class="header-section-number">17.4</span> Resultados finales<a href="modelizacion-estadistica-2.html#resultados-finales" class="anchor-section" aria-label="Anchor link to header"></a></h2>
<p>El proceso de modelización no acaba con la realización del modelo, como se ha indicado, es necesario documentar y presentar los resultados finales para facilitar la puesta en producción del modelo. Este proceso no es obtener unos parámetros y describirlos, este proceso tiene que ayudar a otro equipo a mejorar una operativa, testear el resultado de un medicamento o mejorar una acción comercial como es el caso que está sirviendo de hilo conductor al ensayo. La documentación y el código para la puesta en producción del modelo habrá de incluir:</p>
<ul>
<li><p>Descriptivo de los datos. Origen y tratamiento inicial de los datos además de la aproximación univariable con los principales estadísticos</p></li>
<li><p>Depuración inicial de los datos. En el ejemplo de trabajo se está trabajando con pocas variables pero es posible que se trabajen con miles de ellas y se realizan aproximaciones iniciales para incluir y descartar. En el ejemplo ha aparecido algún caso donde variables no aportaban nada o directamente aportaban ruido y han sido descartadas. Los criterios de inclusión y descarte pueden ser tanto estadísticos como de puro negocio, el número de empleados de una empresa no parece una variable relevante si se trabaja con personas físicas (por ejemplo)</p></li>
<li><p>Selección de parámetros/variables incluidas en el modelo. Una vez determinadas que variables pasan al proceso de modelización ese proceso iterativo ya determina que variables son candidatas a formar parte del modelo. Para ello se pueden emplear tácticas univariables como multivariables con métodos automáticos de selección. Si el científico de datos va a emplear técnicas de modelización lineales puede ser interesante analizar las posibles interacciones entre las variables</p></li>
<li><p>Comportamiento univariable frente a la variable respuesta de las variables seleccionadas para la modelización. Esta parte de la documentación es relevante para que los equipos usuarios de los datos entiendan como van a funcionar esas variables. Es cierto que un modelo matemático es una estructura compleja capaz de ir más allá del comportamiento univariable, pero este análisis ya permite conocer la motivación que ha tenido el modelo para incluir esa variable y pueden servir para identificar indicadores de negocio</p></li>
<li><p>Código empleado para la obtención de los datos y la creación de las variables de entrada. En el ejemplo tratado se han empleado modelos lineales y tenía especial importancia la descripción de los parámetros ofrecidos por el modelo por lo que era imprescindible la reclasificación de factores. Pero, incluso las técnicas de aprendizaje automático más sofisticadas, mejoran con la transformación de las variables de entrada y todo ese código generado también forma parte de la documentación. No será necesario incluir todo el código con los análisis iniciales</p></li>
<li><p>Conjunto de datos de entrenamiento, test y validación. Si es posible almacenar esta información se recomienda conservarla ya que posteriormente puede haber modificaciones en la propia estructura de los datos (una fecha pasa de almacenarse en meses a almacenarse en años por ejemplo) y posteriores desajustes de modelo puedan justificarse de ese modo. Además, el trabajo de los científicos de datos ha de ser auditado periódicamente</p></li>
<li><p>Resultados de los modelos. Bien mediante curva de ganancia, curva ROC o el método que se utilice en el equipo. Eso permite comparar los resultados esperados con la calibración periódica del modelo, comparando lo que se espera del modelo frente a lo que se está obteniendo en la realidad.</p></li>
</ul>
<p>Los elementos señalados con anterioridad son un mínimo exigible para entregar un modelo matemático, además, el científico de datos si trabaja de este modo ha de elaborar una historia con los datos y con todos los pasos que le han llevado a crear ese modelo.</p>

</div>
</div>
            </section>

          </div>
        </div>
      </div>
<a href="modelizacion-estadistica.html" class="navigation navigation-prev navigation-unique" aria-label="Previous page"><i class="fa fa-angle-left"></i></a>

    </div>
  </div>
<script src="libs/gitbook-2.6.7/js/app.min.js"></script>
<script src="libs/gitbook-2.6.7/js/clipboard.min.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-search.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-sharing.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-fontsettings.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-bookdown.js"></script>
<script src="libs/gitbook-2.6.7/js/jquery.highlight.js"></script>
<script src="libs/gitbook-2.6.7/js/plugin-clipboard.js"></script>
<script>
gitbook.require(["gitbook"], function(gitbook) {
gitbook.start({
"sharing": {
"github": false,
"facebook": true,
"twitter": true,
"linkedin": false,
"weibo": false,
"instapaper": false,
"vk": false,
"whatsapp": false,
"all": ["facebook", "twitter", "linkedin", "weibo", "instapaper"]
},
"fontsettings": {
"theme": "white",
"family": "sans",
"size": 2
},
"edit": {
"link": "https://github.com/rvaquerizo02/edit/master/15-Modelizacion-estadistica-2.Rmd",
"text": "Edit"
},
"history": {
"link": null,
"text": null
},
"view": {
"link": null,
"text": null
},
"download": null,
"search": {
"engine": "fuse",
"options": null
},
"toc": {
"collapse": "section"
}
});
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    var src = "true";
    if (src === "" || src === "true") src = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.9/latest.js?config=TeX-MML-AM_CHTML";
    if (location.protocol !== "file:")
      if (/^https?:/.test(src))
        src = src.replace(/^https?:/, '');
    script.src = src;
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>
</body>

</html>
